// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: surchain/provenance/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "surchain.provenance.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /**
   * params defines the module parameters to update.
   *
   * NOTE: All parameters must be supplied.
   */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgRegisterPrincipal registers a new pipeline principal. */
export interface MsgRegisterPrincipal {
  creator: string;
  principalId: string;
  name: string;
  pubkey: Uint8Array;
  principalType: string;
}

/** MsgRegisterPrincipalResponse defines the response for RegisterPrincipal. */
export interface MsgRegisterPrincipalResponse {
}

/** MsgSubmitProvenanceNode submits a provenance node. */
export interface MsgSubmitProvenanceNode {
  creator: string;
  contentHashIn: Uint8Array;
  contentHashOut: Uint8Array;
  transformationType: string;
  principalId: string;
  sig: Uint8Array;
}

/** MsgSubmitProvenanceNodeResponse defines the response for SubmitProvenanceNode. */
export interface MsgSubmitProvenanceNodeResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgRegisterPrincipal(): MsgRegisterPrincipal {
  return { creator: "", principalId: "", name: "", pubkey: new Uint8Array(0), principalType: "" };
}

export const MsgRegisterPrincipal: MessageFns<MsgRegisterPrincipal> = {
  encode(message: MsgRegisterPrincipal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.principalId !== "") {
      writer.uint32(18).string(message.principalId);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.pubkey.length !== 0) {
      writer.uint32(34).bytes(message.pubkey);
    }
    if (message.principalType !== "") {
      writer.uint32(42).string(message.principalType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterPrincipal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterPrincipal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.principalId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.pubkey = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.principalType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterPrincipal {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      principalId: isSet(object.principalId)
        ? globalThis.String(object.principalId)
        : isSet(object.principal_id)
        ? globalThis.String(object.principal_id)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      pubkey: isSet(object.pubkey) ? bytesFromBase64(object.pubkey) : new Uint8Array(0),
      principalType: isSet(object.principalType)
        ? globalThis.String(object.principalType)
        : isSet(object.principal_type)
        ? globalThis.String(object.principal_type)
        : "",
    };
  },

  toJSON(message: MsgRegisterPrincipal): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.principalId !== "") {
      obj.principalId = message.principalId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.pubkey.length !== 0) {
      obj.pubkey = base64FromBytes(message.pubkey);
    }
    if (message.principalType !== "") {
      obj.principalType = message.principalType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterPrincipal>, I>>(base?: I): MsgRegisterPrincipal {
    return MsgRegisterPrincipal.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterPrincipal>, I>>(object: I): MsgRegisterPrincipal {
    const message = createBaseMsgRegisterPrincipal();
    message.creator = object.creator ?? "";
    message.principalId = object.principalId ?? "";
    message.name = object.name ?? "";
    message.pubkey = object.pubkey ?? new Uint8Array(0);
    message.principalType = object.principalType ?? "";
    return message;
  },
};

function createBaseMsgRegisterPrincipalResponse(): MsgRegisterPrincipalResponse {
  return {};
}

export const MsgRegisterPrincipalResponse: MessageFns<MsgRegisterPrincipalResponse> = {
  encode(_: MsgRegisterPrincipalResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterPrincipalResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterPrincipalResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgRegisterPrincipalResponse {
    return {};
  },

  toJSON(_: MsgRegisterPrincipalResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterPrincipalResponse>, I>>(base?: I): MsgRegisterPrincipalResponse {
    return MsgRegisterPrincipalResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterPrincipalResponse>, I>>(_: I): MsgRegisterPrincipalResponse {
    const message = createBaseMsgRegisterPrincipalResponse();
    return message;
  },
};

function createBaseMsgSubmitProvenanceNode(): MsgSubmitProvenanceNode {
  return {
    creator: "",
    contentHashIn: new Uint8Array(0),
    contentHashOut: new Uint8Array(0),
    transformationType: "",
    principalId: "",
    sig: new Uint8Array(0),
  };
}

export const MsgSubmitProvenanceNode: MessageFns<MsgSubmitProvenanceNode> = {
  encode(message: MsgSubmitProvenanceNode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.contentHashIn.length !== 0) {
      writer.uint32(18).bytes(message.contentHashIn);
    }
    if (message.contentHashOut.length !== 0) {
      writer.uint32(26).bytes(message.contentHashOut);
    }
    if (message.transformationType !== "") {
      writer.uint32(34).string(message.transformationType);
    }
    if (message.principalId !== "") {
      writer.uint32(42).string(message.principalId);
    }
    if (message.sig.length !== 0) {
      writer.uint32(50).bytes(message.sig);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitProvenanceNode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitProvenanceNode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.contentHashIn = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentHashOut = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.transformationType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.principalId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.sig = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitProvenanceNode {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      contentHashIn: isSet(object.contentHashIn)
        ? bytesFromBase64(object.contentHashIn)
        : isSet(object.content_hash_in)
        ? bytesFromBase64(object.content_hash_in)
        : new Uint8Array(0),
      contentHashOut: isSet(object.contentHashOut)
        ? bytesFromBase64(object.contentHashOut)
        : isSet(object.content_hash_out)
        ? bytesFromBase64(object.content_hash_out)
        : new Uint8Array(0),
      transformationType: isSet(object.transformationType)
        ? globalThis.String(object.transformationType)
        : isSet(object.transformation_type)
        ? globalThis.String(object.transformation_type)
        : "",
      principalId: isSet(object.principalId)
        ? globalThis.String(object.principalId)
        : isSet(object.principal_id)
        ? globalThis.String(object.principal_id)
        : "",
      sig: isSet(object.sig) ? bytesFromBase64(object.sig) : new Uint8Array(0),
    };
  },

  toJSON(message: MsgSubmitProvenanceNode): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.contentHashIn.length !== 0) {
      obj.contentHashIn = base64FromBytes(message.contentHashIn);
    }
    if (message.contentHashOut.length !== 0) {
      obj.contentHashOut = base64FromBytes(message.contentHashOut);
    }
    if (message.transformationType !== "") {
      obj.transformationType = message.transformationType;
    }
    if (message.principalId !== "") {
      obj.principalId = message.principalId;
    }
    if (message.sig.length !== 0) {
      obj.sig = base64FromBytes(message.sig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitProvenanceNode>, I>>(base?: I): MsgSubmitProvenanceNode {
    return MsgSubmitProvenanceNode.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitProvenanceNode>, I>>(object: I): MsgSubmitProvenanceNode {
    const message = createBaseMsgSubmitProvenanceNode();
    message.creator = object.creator ?? "";
    message.contentHashIn = object.contentHashIn ?? new Uint8Array(0);
    message.contentHashOut = object.contentHashOut ?? new Uint8Array(0);
    message.transformationType = object.transformationType ?? "";
    message.principalId = object.principalId ?? "";
    message.sig = object.sig ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgSubmitProvenanceNodeResponse(): MsgSubmitProvenanceNodeResponse {
  return {};
}

export const MsgSubmitProvenanceNodeResponse: MessageFns<MsgSubmitProvenanceNodeResponse> = {
  encode(_: MsgSubmitProvenanceNodeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitProvenanceNodeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitProvenanceNodeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSubmitProvenanceNodeResponse {
    return {};
  },

  toJSON(_: MsgSubmitProvenanceNodeResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitProvenanceNodeResponse>, I>>(base?: I): MsgSubmitProvenanceNodeResponse {
    return MsgSubmitProvenanceNodeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitProvenanceNodeResponse>, I>>(_: I): MsgSubmitProvenanceNodeResponse {
    const message = createBaseMsgSubmitProvenanceNodeResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** RegisterPrincipal registers a new pipeline principal. */
  RegisterPrincipal(request: MsgRegisterPrincipal): Promise<MsgRegisterPrincipalResponse>;
  /** SubmitProvenanceNode submits a provenance node linking input to output content. */
  SubmitProvenanceNode(request: MsgSubmitProvenanceNode): Promise<MsgSubmitProvenanceNodeResponse>;
}

export const MsgServiceName = "surchain.provenance.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.RegisterPrincipal = this.RegisterPrincipal.bind(this);
    this.SubmitProvenanceNode = this.SubmitProvenanceNode.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  RegisterPrincipal(request: MsgRegisterPrincipal): Promise<MsgRegisterPrincipalResponse> {
    const data = MsgRegisterPrincipal.encode(request).finish();
    const promise = this.rpc.request(this.service, "RegisterPrincipal", data);
    return promise.then((data) => MsgRegisterPrincipalResponse.decode(new BinaryReader(data)));
  }

  SubmitProvenanceNode(request: MsgSubmitProvenanceNode): Promise<MsgSubmitProvenanceNodeResponse> {
    const data = MsgSubmitProvenanceNode.encode(request).finish();
    const promise = this.rpc.request(this.service, "SubmitProvenanceNode", data);
    return promise.then((data) => MsgSubmitProvenanceNodeResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
