// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: surchain/provenance/v1/types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "surchain.provenance.v1";

/** PipelinePrincipal represents a registered pipeline operator. */
export interface PipelinePrincipal {
  principalId: string;
  name: string;
  pubkey: Uint8Array;
  principalType: string;
  registeredAt: number;
}

/** ProvenanceNode represents a single transform in a content processing pipeline. */
export interface ProvenanceNode {
  nodeId: string;
  contentHashIn: Uint8Array;
  contentHashOut: Uint8Array;
  transformationType: string;
  principalId: string;
  timestamp: number;
}

function createBasePipelinePrincipal(): PipelinePrincipal {
  return { principalId: "", name: "", pubkey: new Uint8Array(0), principalType: "", registeredAt: 0 };
}

export const PipelinePrincipal: MessageFns<PipelinePrincipal> = {
  encode(message: PipelinePrincipal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.principalId !== "") {
      writer.uint32(10).string(message.principalId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.pubkey.length !== 0) {
      writer.uint32(26).bytes(message.pubkey);
    }
    if (message.principalType !== "") {
      writer.uint32(34).string(message.principalType);
    }
    if (message.registeredAt !== 0) {
      writer.uint32(40).int64(message.registeredAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PipelinePrincipal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePipelinePrincipal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.principalId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pubkey = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.principalType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.registeredAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PipelinePrincipal {
    return {
      principalId: isSet(object.principalId)
        ? globalThis.String(object.principalId)
        : isSet(object.principal_id)
        ? globalThis.String(object.principal_id)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      pubkey: isSet(object.pubkey) ? bytesFromBase64(object.pubkey) : new Uint8Array(0),
      principalType: isSet(object.principalType)
        ? globalThis.String(object.principalType)
        : isSet(object.principal_type)
        ? globalThis.String(object.principal_type)
        : "",
      registeredAt: isSet(object.registeredAt)
        ? globalThis.Number(object.registeredAt)
        : isSet(object.registered_at)
        ? globalThis.Number(object.registered_at)
        : 0,
    };
  },

  toJSON(message: PipelinePrincipal): unknown {
    const obj: any = {};
    if (message.principalId !== "") {
      obj.principalId = message.principalId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.pubkey.length !== 0) {
      obj.pubkey = base64FromBytes(message.pubkey);
    }
    if (message.principalType !== "") {
      obj.principalType = message.principalType;
    }
    if (message.registeredAt !== 0) {
      obj.registeredAt = Math.round(message.registeredAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PipelinePrincipal>, I>>(base?: I): PipelinePrincipal {
    return PipelinePrincipal.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PipelinePrincipal>, I>>(object: I): PipelinePrincipal {
    const message = createBasePipelinePrincipal();
    message.principalId = object.principalId ?? "";
    message.name = object.name ?? "";
    message.pubkey = object.pubkey ?? new Uint8Array(0);
    message.principalType = object.principalType ?? "";
    message.registeredAt = object.registeredAt ?? 0;
    return message;
  },
};

function createBaseProvenanceNode(): ProvenanceNode {
  return {
    nodeId: "",
    contentHashIn: new Uint8Array(0),
    contentHashOut: new Uint8Array(0),
    transformationType: "",
    principalId: "",
    timestamp: 0,
  };
}

export const ProvenanceNode: MessageFns<ProvenanceNode> = {
  encode(message: ProvenanceNode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== "") {
      writer.uint32(10).string(message.nodeId);
    }
    if (message.contentHashIn.length !== 0) {
      writer.uint32(18).bytes(message.contentHashIn);
    }
    if (message.contentHashOut.length !== 0) {
      writer.uint32(26).bytes(message.contentHashOut);
    }
    if (message.transformationType !== "") {
      writer.uint32(34).string(message.transformationType);
    }
    if (message.principalId !== "") {
      writer.uint32(42).string(message.principalId);
    }
    if (message.timestamp !== 0) {
      writer.uint32(48).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProvenanceNode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProvenanceNode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.contentHashIn = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentHashOut = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.transformationType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.principalId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProvenanceNode {
    return {
      nodeId: isSet(object.nodeId)
        ? globalThis.String(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.String(object.node_id)
        : "",
      contentHashIn: isSet(object.contentHashIn)
        ? bytesFromBase64(object.contentHashIn)
        : isSet(object.content_hash_in)
        ? bytesFromBase64(object.content_hash_in)
        : new Uint8Array(0),
      contentHashOut: isSet(object.contentHashOut)
        ? bytesFromBase64(object.contentHashOut)
        : isSet(object.content_hash_out)
        ? bytesFromBase64(object.content_hash_out)
        : new Uint8Array(0),
      transformationType: isSet(object.transformationType)
        ? globalThis.String(object.transformationType)
        : isSet(object.transformation_type)
        ? globalThis.String(object.transformation_type)
        : "",
      principalId: isSet(object.principalId)
        ? globalThis.String(object.principalId)
        : isSet(object.principal_id)
        ? globalThis.String(object.principal_id)
        : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: ProvenanceNode): unknown {
    const obj: any = {};
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    if (message.contentHashIn.length !== 0) {
      obj.contentHashIn = base64FromBytes(message.contentHashIn);
    }
    if (message.contentHashOut.length !== 0) {
      obj.contentHashOut = base64FromBytes(message.contentHashOut);
    }
    if (message.transformationType !== "") {
      obj.transformationType = message.transformationType;
    }
    if (message.principalId !== "") {
      obj.principalId = message.principalId;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProvenanceNode>, I>>(base?: I): ProvenanceNode {
    return ProvenanceNode.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProvenanceNode>, I>>(object: I): ProvenanceNode {
    const message = createBaseProvenanceNode();
    message.nodeId = object.nodeId ?? "";
    message.contentHashIn = object.contentHashIn ?? new Uint8Array(0);
    message.contentHashOut = object.contentHashOut ?? new Uint8Array(0);
    message.transformationType = object.transformationType ?? "";
    message.principalId = object.principalId ?? "";
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
