// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/surchain/identity/v1/tx";
import { MsgRegisterUsername } from "./types/surchain/identity/v1/tx";
import { MsgAddDevice } from "./types/surchain/identity/v1/tx";
import { MsgRevokeDevice } from "./types/surchain/identity/v1/tx";

import { Params as typeParams} from "./types"
import { UserProfile as typeUserProfile} from "./types"
import { DeviceCommitment as typeDeviceCommitment} from "./types"

export { MsgUpdateParams, MsgRegisterUsername, MsgAddDevice, MsgRevokeDevice };

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgRegisterUsernameParams = {
  value: MsgRegisterUsername,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddDeviceParams = {
  value: MsgAddDevice,
  fee?: StdFee,
  memo?: string
};

type sendMsgRevokeDeviceParams = {
  value: MsgRevokeDevice,
  fee?: StdFee,
  memo?: string
};


type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgRegisterUsernameParams = {
  value: MsgRegisterUsername,
};

type msgAddDeviceParams = {
  value: MsgAddDevice,
};

type msgRevokeDeviceParams = {
  value: MsgRevokeDevice,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRegisterUsername({ value, fee, memo }: sendMsgRegisterUsernameParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegisterUsername: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRegisterUsername({ value: MsgRegisterUsername.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegisterUsername: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddDevice({ value, fee, memo }: sendMsgAddDeviceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddDevice: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgAddDevice({ value: MsgAddDevice.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddDevice: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRevokeDevice({ value, fee, memo }: sendMsgRevokeDeviceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRevokeDevice: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRevokeDevice({ value: MsgRevokeDevice.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRevokeDevice: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/surchain.identity.v1.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgRegisterUsername({ value }: msgRegisterUsernameParams): EncodeObject {
			try {
				return { typeUrl: "/surchain.identity.v1.MsgRegisterUsername", value: MsgRegisterUsername.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegisterUsername: Could not create message: ' + e.message)
			}
		},
		
		msgAddDevice({ value }: msgAddDeviceParams): EncodeObject {
			try {
				return { typeUrl: "/surchain.identity.v1.MsgAddDevice", value: MsgAddDevice.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddDevice: Could not create message: ' + e.message)
			}
		},
		
		msgRevokeDevice({ value }: msgRevokeDeviceParams): EncodeObject {
			try {
				return { typeUrl: "/surchain.identity.v1.MsgRevokeDevice", value: MsgRevokeDevice.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRevokeDevice: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Params: getStructure(typeParams.fromPartial({})),
						UserProfile: getStructure(typeUserProfile.fromPartial({})),
						DeviceCommitment: getStructure(typeDeviceCommitment.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			SurchainIdentityV_1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;