// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/surchain/provenance/v1/tx";
import { MsgRegisterPrincipal } from "./types/surchain/provenance/v1/tx";
import { MsgSubmitProvenanceNode } from "./types/surchain/provenance/v1/tx";

import { Params as typeParams} from "./types"
import { PipelinePrincipal as typePipelinePrincipal} from "./types"
import { ProvenanceNode as typeProvenanceNode} from "./types"

export { MsgUpdateParams, MsgRegisterPrincipal, MsgSubmitProvenanceNode };

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgRegisterPrincipalParams = {
  value: MsgRegisterPrincipal,
  fee?: StdFee,
  memo?: string
};

type sendMsgSubmitProvenanceNodeParams = {
  value: MsgSubmitProvenanceNode,
  fee?: StdFee,
  memo?: string
};


type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgRegisterPrincipalParams = {
  value: MsgRegisterPrincipal,
};

type msgSubmitProvenanceNodeParams = {
  value: MsgSubmitProvenanceNode,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRegisterPrincipal({ value, fee, memo }: sendMsgRegisterPrincipalParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegisterPrincipal: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgRegisterPrincipal({ value: MsgRegisterPrincipal.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegisterPrincipal: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSubmitProvenanceNode({ value, fee, memo }: sendMsgSubmitProvenanceNodeParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSubmitProvenanceNode: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgSubmitProvenanceNode({ value: MsgSubmitProvenanceNode.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSubmitProvenanceNode: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/surchain.provenance.v1.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgRegisterPrincipal({ value }: msgRegisterPrincipalParams): EncodeObject {
			try {
				return { typeUrl: "/surchain.provenance.v1.MsgRegisterPrincipal", value: MsgRegisterPrincipal.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegisterPrincipal: Could not create message: ' + e.message)
			}
		},
		
		msgSubmitProvenanceNode({ value }: msgSubmitProvenanceNodeParams): EncodeObject {
			try {
				return { typeUrl: "/surchain.provenance.v1.MsgSubmitProvenanceNode", value: MsgSubmitProvenanceNode.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSubmitProvenanceNode: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Params: getStructure(typeParams.fromPartial({})),
						PipelinePrincipal: getStructure(typePipelinePrincipal.fromPartial({})),
						ProvenanceNode: getStructure(typeProvenanceNode.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			SurchainProvenanceV_1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;