// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: surchain/attestation/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "surchain.attestation.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /**
   * params defines the module parameters to update.
   *
   * NOTE: All parameters must be supplied.
   */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgSubmitAttestation submits a ZK-proven content attestation. */
export interface MsgSubmitAttestation {
  creator: string;
  username: string;
  contentHash: Uint8Array;
  nullifier: Uint8Array;
  commitmentRoot: Uint8Array;
  proofBytes: Uint8Array;
  /**
   * Provenance class of the content. Empty or "human_keyboard" => a Sur Keyboard
   * human-typing attestation backed by the Groth16 proof above. Other values
   * ("device_authored", "ai_generated", "external_source", "imported") are
   * device-signed DECLARATIONS — they do NOT assert human typing and are secured
   * by the device signature below instead of the ZK proof.
   */
  origin: string;
  /** Optional citation for "external_source" / "imported" (e.g. a URL, book, note). */
  citation: string;
  /**
   * Compressed secp256k1 device public key (must hash to the device id in
   * `username`). Required for declaration origins; unused for human_keyboard.
   */
  devicePubkey: Uint8Array;
  /**
   * secp256k1 signature over SHA-256(content_hash || origin || citation || nullifier),
   * proving the device made this declaration. Required for declaration origins.
   */
  deviceSignature: Uint8Array;
}

/** MsgSubmitAttestationResponse defines the response for SubmitAttestation. */
export interface MsgSubmitAttestationResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgSubmitAttestation(): MsgSubmitAttestation {
  return {
    creator: "",
    username: "",
    contentHash: new Uint8Array(0),
    nullifier: new Uint8Array(0),
    commitmentRoot: new Uint8Array(0),
    proofBytes: new Uint8Array(0),
    origin: "",
    citation: "",
    devicePubkey: new Uint8Array(0),
    deviceSignature: new Uint8Array(0),
  };
}

export const MsgSubmitAttestation: MessageFns<MsgSubmitAttestation> = {
  encode(message: MsgSubmitAttestation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    if (message.contentHash.length !== 0) {
      writer.uint32(26).bytes(message.contentHash);
    }
    if (message.nullifier.length !== 0) {
      writer.uint32(34).bytes(message.nullifier);
    }
    if (message.commitmentRoot.length !== 0) {
      writer.uint32(42).bytes(message.commitmentRoot);
    }
    if (message.proofBytes.length !== 0) {
      writer.uint32(50).bytes(message.proofBytes);
    }
    if (message.origin !== "") {
      writer.uint32(58).string(message.origin);
    }
    if (message.citation !== "") {
      writer.uint32(66).string(message.citation);
    }
    if (message.devicePubkey.length !== 0) {
      writer.uint32(74).bytes(message.devicePubkey);
    }
    if (message.deviceSignature.length !== 0) {
      writer.uint32(82).bytes(message.deviceSignature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitAttestation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitAttestation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentHash = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nullifier = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.commitmentRoot = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.proofBytes = reader.bytes();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.origin = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.citation = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.devicePubkey = reader.bytes();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.deviceSignature = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitAttestation {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      contentHash: isSet(object.contentHash)
        ? bytesFromBase64(object.contentHash)
        : isSet(object.content_hash)
        ? bytesFromBase64(object.content_hash)
        : new Uint8Array(0),
      nullifier: isSet(object.nullifier) ? bytesFromBase64(object.nullifier) : new Uint8Array(0),
      commitmentRoot: isSet(object.commitmentRoot)
        ? bytesFromBase64(object.commitmentRoot)
        : isSet(object.commitment_root)
        ? bytesFromBase64(object.commitment_root)
        : new Uint8Array(0),
      proofBytes: isSet(object.proofBytes)
        ? bytesFromBase64(object.proofBytes)
        : isSet(object.proof_bytes)
        ? bytesFromBase64(object.proof_bytes)
        : new Uint8Array(0),
      origin: isSet(object.origin) ? globalThis.String(object.origin) : "",
      citation: isSet(object.citation) ? globalThis.String(object.citation) : "",
      devicePubkey: isSet(object.devicePubkey)
        ? bytesFromBase64(object.devicePubkey)
        : isSet(object.device_pubkey)
        ? bytesFromBase64(object.device_pubkey)
        : new Uint8Array(0),
      deviceSignature: isSet(object.deviceSignature)
        ? bytesFromBase64(object.deviceSignature)
        : isSet(object.device_signature)
        ? bytesFromBase64(object.device_signature)
        : new Uint8Array(0),
    };
  },

  toJSON(message: MsgSubmitAttestation): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.contentHash.length !== 0) {
      obj.contentHash = base64FromBytes(message.contentHash);
    }
    if (message.nullifier.length !== 0) {
      obj.nullifier = base64FromBytes(message.nullifier);
    }
    if (message.commitmentRoot.length !== 0) {
      obj.commitmentRoot = base64FromBytes(message.commitmentRoot);
    }
    if (message.proofBytes.length !== 0) {
      obj.proofBytes = base64FromBytes(message.proofBytes);
    }
    if (message.origin !== "") {
      obj.origin = message.origin;
    }
    if (message.citation !== "") {
      obj.citation = message.citation;
    }
    if (message.devicePubkey.length !== 0) {
      obj.devicePubkey = base64FromBytes(message.devicePubkey);
    }
    if (message.deviceSignature.length !== 0) {
      obj.deviceSignature = base64FromBytes(message.deviceSignature);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitAttestation>, I>>(base?: I): MsgSubmitAttestation {
    return MsgSubmitAttestation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitAttestation>, I>>(object: I): MsgSubmitAttestation {
    const message = createBaseMsgSubmitAttestation();
    message.creator = object.creator ?? "";
    message.username = object.username ?? "";
    message.contentHash = object.contentHash ?? new Uint8Array(0);
    message.nullifier = object.nullifier ?? new Uint8Array(0);
    message.commitmentRoot = object.commitmentRoot ?? new Uint8Array(0);
    message.proofBytes = object.proofBytes ?? new Uint8Array(0);
    message.origin = object.origin ?? "";
    message.citation = object.citation ?? "";
    message.devicePubkey = object.devicePubkey ?? new Uint8Array(0);
    message.deviceSignature = object.deviceSignature ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgSubmitAttestationResponse(): MsgSubmitAttestationResponse {
  return {};
}

export const MsgSubmitAttestationResponse: MessageFns<MsgSubmitAttestationResponse> = {
  encode(_: MsgSubmitAttestationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitAttestationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitAttestationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSubmitAttestationResponse {
    return {};
  },

  toJSON(_: MsgSubmitAttestationResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitAttestationResponse>, I>>(base?: I): MsgSubmitAttestationResponse {
    return MsgSubmitAttestationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitAttestationResponse>, I>>(_: I): MsgSubmitAttestationResponse {
    const message = createBaseMsgSubmitAttestationResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /** SubmitAttestation submits a ZK-proven content attestation. */
  SubmitAttestation(request: MsgSubmitAttestation): Promise<MsgSubmitAttestationResponse>;
}

export const MsgServiceName = "surchain.attestation.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.SubmitAttestation = this.SubmitAttestation.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  SubmitAttestation(request: MsgSubmitAttestation): Promise<MsgSubmitAttestationResponse> {
    const data = MsgSubmitAttestation.encode(request).finish();
    const promise = this.rpc.request(this.service, "SubmitAttestation", data);
    return promise.then((data) => MsgSubmitAttestationResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
