// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: surchain/attestation/v1/types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "surchain.attestation.v1";

/** AttestationRecord represents a submitted ZK content attestation. */
export interface AttestationRecord {
  username: string;
  contentHash: Uint8Array;
  nullifier: Uint8Array;
  commitmentRoot: Uint8Array;
  timestamp: number;
  /**
   * Provenance class: "human_keyboard" (ZK-proven human typing) or a device-signed
   * declaration ("device_authored", "ai_generated", "external_source", "imported").
   */
  origin: string;
  /** Optional citation for declaration origins (URL, book, note). */
  citation: string;
}

function createBaseAttestationRecord(): AttestationRecord {
  return {
    username: "",
    contentHash: new Uint8Array(0),
    nullifier: new Uint8Array(0),
    commitmentRoot: new Uint8Array(0),
    timestamp: 0,
    origin: "",
    citation: "",
  };
}

export const AttestationRecord: MessageFns<AttestationRecord> = {
  encode(message: AttestationRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.contentHash.length !== 0) {
      writer.uint32(18).bytes(message.contentHash);
    }
    if (message.nullifier.length !== 0) {
      writer.uint32(26).bytes(message.nullifier);
    }
    if (message.commitmentRoot.length !== 0) {
      writer.uint32(34).bytes(message.commitmentRoot);
    }
    if (message.timestamp !== 0) {
      writer.uint32(40).int64(message.timestamp);
    }
    if (message.origin !== "") {
      writer.uint32(50).string(message.origin);
    }
    if (message.citation !== "") {
      writer.uint32(58).string(message.citation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AttestationRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAttestationRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.contentHash = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nullifier = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.commitmentRoot = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.origin = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.citation = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AttestationRecord {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      contentHash: isSet(object.contentHash)
        ? bytesFromBase64(object.contentHash)
        : isSet(object.content_hash)
        ? bytesFromBase64(object.content_hash)
        : new Uint8Array(0),
      nullifier: isSet(object.nullifier) ? bytesFromBase64(object.nullifier) : new Uint8Array(0),
      commitmentRoot: isSet(object.commitmentRoot)
        ? bytesFromBase64(object.commitmentRoot)
        : isSet(object.commitment_root)
        ? bytesFromBase64(object.commitment_root)
        : new Uint8Array(0),
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      origin: isSet(object.origin) ? globalThis.String(object.origin) : "",
      citation: isSet(object.citation) ? globalThis.String(object.citation) : "",
    };
  },

  toJSON(message: AttestationRecord): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.contentHash.length !== 0) {
      obj.contentHash = base64FromBytes(message.contentHash);
    }
    if (message.nullifier.length !== 0) {
      obj.nullifier = base64FromBytes(message.nullifier);
    }
    if (message.commitmentRoot.length !== 0) {
      obj.commitmentRoot = base64FromBytes(message.commitmentRoot);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.origin !== "") {
      obj.origin = message.origin;
    }
    if (message.citation !== "") {
      obj.citation = message.citation;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AttestationRecord>, I>>(base?: I): AttestationRecord {
    return AttestationRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AttestationRecord>, I>>(object: I): AttestationRecord {
    const message = createBaseAttestationRecord();
    message.username = object.username ?? "";
    message.contentHash = object.contentHash ?? new Uint8Array(0);
    message.nullifier = object.nullifier ?? new Uint8Array(0);
    message.commitmentRoot = object.commitmentRoot ?? new Uint8Array(0);
    message.timestamp = object.timestamp ?? 0;
    message.origin = object.origin ?? "";
    message.citation = object.citation ?? "";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
