// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: surchain/provenance/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the module parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e44dbb7b952b7024, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e44dbb7b952b7024, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgRegisterPrincipal registers a new pipeline principal.
type MsgRegisterPrincipal struct {
	Creator       string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PrincipalId   string `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Pubkey        []byte `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	PrincipalType string `protobuf:"bytes,5,opt,name=principal_type,json=principalType,proto3" json:"principal_type,omitempty"`
	// Optional origin domain this principal claims (see PipelinePrincipal.domain
	// for the off-chain /.well-known verification flow).
	Domain string `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (m *MsgRegisterPrincipal) Reset()         { *m = MsgRegisterPrincipal{} }
func (m *MsgRegisterPrincipal) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterPrincipal) ProtoMessage()    {}
func (*MsgRegisterPrincipal) Descriptor() ([]byte, []int) {
	return fileDescriptor_e44dbb7b952b7024, []int{2}
}
func (m *MsgRegisterPrincipal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterPrincipal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterPrincipal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterPrincipal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterPrincipal.Merge(m, src)
}
func (m *MsgRegisterPrincipal) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterPrincipal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterPrincipal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterPrincipal proto.InternalMessageInfo

func (m *MsgRegisterPrincipal) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterPrincipal) GetPrincipalId() string {
	if m != nil {
		return m.PrincipalId
	}
	return ""
}

func (m *MsgRegisterPrincipal) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgRegisterPrincipal) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *MsgRegisterPrincipal) GetPrincipalType() string {
	if m != nil {
		return m.PrincipalType
	}
	return ""
}

func (m *MsgRegisterPrincipal) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

// MsgRegisterPrincipalResponse defines the response for RegisterPrincipal.
type MsgRegisterPrincipalResponse struct {
}

func (m *MsgRegisterPrincipalResponse) Reset()         { *m = MsgRegisterPrincipalResponse{} }
func (m *MsgRegisterPrincipalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterPrincipalResponse) ProtoMessage()    {}
func (*MsgRegisterPrincipalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e44dbb7b952b7024, []int{3}
}
func (m *MsgRegisterPrincipalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterPrincipalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterPrincipalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterPrincipalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterPrincipalResponse.Merge(m, src)
}
func (m *MsgRegisterPrincipalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterPrincipalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterPrincipalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterPrincipalResponse proto.InternalMessageInfo

// MsgSubmitProvenanceNode submits a provenance node.
type MsgSubmitProvenanceNode struct {
	Creator            string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ContentHashIn      []byte `protobuf:"bytes,2,opt,name=content_hash_in,json=contentHashIn,proto3" json:"content_hash_in,omitempty"`
	ContentHashOut     []byte `protobuf:"bytes,3,opt,name=content_hash_out,json=contentHashOut,proto3" json:"content_hash_out,omitempty"`
	TransformationType string `protobuf:"bytes,4,opt,name=transformation_type,json=transformationType,proto3" json:"transformation_type,omitempty"`
	PrincipalId        string `protobuf:"bytes,5,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	Sig                []byte `protobuf:"bytes,6,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (m *MsgSubmitProvenanceNode) Reset()         { *m = MsgSubmitProvenanceNode{} }
func (m *MsgSubmitProvenanceNode) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitProvenanceNode) ProtoMessage()    {}
func (*MsgSubmitProvenanceNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_e44dbb7b952b7024, []int{4}
}
func (m *MsgSubmitProvenanceNode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitProvenanceNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitProvenanceNode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitProvenanceNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitProvenanceNode.Merge(m, src)
}
func (m *MsgSubmitProvenanceNode) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitProvenanceNode) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitProvenanceNode.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitProvenanceNode proto.InternalMessageInfo

func (m *MsgSubmitProvenanceNode) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitProvenanceNode) GetContentHashIn() []byte {
	if m != nil {
		return m.ContentHashIn
	}
	return nil
}

func (m *MsgSubmitProvenanceNode) GetContentHashOut() []byte {
	if m != nil {
		return m.ContentHashOut
	}
	return nil
}

func (m *MsgSubmitProvenanceNode) GetTransformationType() string {
	if m != nil {
		return m.TransformationType
	}
	return ""
}

func (m *MsgSubmitProvenanceNode) GetPrincipalId() string {
	if m != nil {
		return m.PrincipalId
	}
	return ""
}

func (m *MsgSubmitProvenanceNode) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

// MsgSubmitProvenanceNodeResponse defines the response for SubmitProvenanceNode.
type MsgSubmitProvenanceNodeResponse struct {
}

func (m *MsgSubmitProvenanceNodeResponse) Reset()         { *m = MsgSubmitProvenanceNodeResponse{} }
func (m *MsgSubmitProvenanceNodeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitProvenanceNodeResponse) ProtoMessage()    {}
func (*MsgSubmitProvenanceNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e44dbb7b952b7024, []int{5}
}
func (m *MsgSubmitProvenanceNodeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitProvenanceNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitProvenanceNodeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitProvenanceNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitProvenanceNodeResponse.Merge(m, src)
}
func (m *MsgSubmitProvenanceNodeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitProvenanceNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitProvenanceNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitProvenanceNodeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "surchain.provenance.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "surchain.provenance.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgRegisterPrincipal)(nil), "surchain.provenance.v1.MsgRegisterPrincipal")
	proto.RegisterType((*MsgRegisterPrincipalResponse)(nil), "surchain.provenance.v1.MsgRegisterPrincipalResponse")
	proto.RegisterType((*MsgSubmitProvenanceNode)(nil), "surchain.provenance.v1.MsgSubmitProvenanceNode")
	proto.RegisterType((*MsgSubmitProvenanceNodeResponse)(nil), "surchain.provenance.v1.MsgSubmitProvenanceNodeResponse")
}

func init() { proto.RegisterFile("surchain/provenance/v1/tx.proto", fileDescriptor_e44dbb7b952b7024) }

var fileDescriptor_e44dbb7b952b7024 = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x4f, 0xd4, 0x40,
	0x18, 0xde, 0xf2, 0xb1, 0x66, 0x87, 0xf2, 0x35, 0x6e, 0xa0, 0x34, 0xa6, 0xc0, 0x1a, 0x74, 0x43,
	0xb4, 0x0d, 0xab, 0x51, 0xc3, 0x0d, 0x4e, 0x92, 0x88, 0x92, 0xa2, 0x17, 0x2f, 0x9b, 0xd9, 0x76,
	0x6c, 0x27, 0xd2, 0x99, 0x66, 0x66, 0x8a, 0xec, 0x8d, 0x78, 0xf4, 0x64, 0xe2, 0x9f, 0xf0, 0xc8,
	0xc1, 0xdf, 0x60, 0x38, 0x12, 0x4f, 0x9e, 0x8c, 0x81, 0x44, 0xee, 0xfe, 0x02, 0xd3, 0xe9, 0xc7,
	0xc2, 0xb2, 0xa0, 0x78, 0x69, 0xe6, 0x7d, 0xdf, 0xe7, 0xfd, 0x78, 0x9e, 0x79, 0x3b, 0x60, 0x5e,
	0x24, 0xdc, 0x0b, 0x11, 0xa1, 0x4e, 0xcc, 0xd9, 0x2e, 0xa6, 0x88, 0x7a, 0xd8, 0xd9, 0x5d, 0x71,
	0xe4, 0x9e, 0x1d, 0x73, 0x26, 0x19, 0x9c, 0x29, 0x00, 0x76, 0x0f, 0x60, 0xef, 0xae, 0x98, 0xd3,
	0x28, 0x22, 0x94, 0x39, 0xea, 0x9b, 0x41, 0xcd, 0x59, 0x8f, 0x89, 0x88, 0x09, 0x27, 0x12, 0x41,
	0x5a, 0x22, 0x12, 0x41, 0x1e, 0x98, 0xcb, 0x02, 0x6d, 0x65, 0x39, 0x99, 0x91, 0x87, 0xea, 0x01,
	0x0b, 0x58, 0xe6, 0x4f, 0x4f, 0xb9, 0xf7, 0xf6, 0x25, 0x53, 0xc5, 0x88, 0xa3, 0x28, 0x4f, 0x6d,
	0x7c, 0xd5, 0xc0, 0xe4, 0xa6, 0x08, 0x5e, 0xc5, 0x3e, 0x92, 0x78, 0x4b, 0x45, 0xe0, 0x23, 0x50,
	0x43, 0x89, 0x0c, 0x19, 0x27, 0xb2, 0x6b, 0x68, 0x0b, 0x5a, 0xb3, 0xb6, 0x6e, 0x7c, 0xfb, 0x72,
	0xbf, 0x9e, 0xf7, 0x5c, 0xf3, 0x7d, 0x8e, 0x85, 0xd8, 0x96, 0x9c, 0xd0, 0xc0, 0xed, 0x41, 0xe1,
	0x1a, 0xa8, 0x66, 0xb5, 0x8d, 0xa1, 0x05, 0xad, 0x39, 0xd6, 0xb2, 0xec, 0xc1, 0xb4, 0xed, 0xac,
	0xcf, 0x7a, 0xed, 0xf0, 0xc7, 0x7c, 0xe5, 0xf3, 0xe9, 0xc1, 0xb2, 0xe6, 0xe6, 0x89, 0xab, 0x4f,
	0xde, 0x9f, 0x1e, 0x2c, 0xf7, 0x4a, 0x7e, 0x38, 0x3d, 0x58, 0x5e, 0x2a, 0x69, 0xec, 0x9d, 0x25,
	0xd2, 0x37, 0x74, 0x63, 0x0e, 0xcc, 0xf6, 0xb9, 0x5c, 0x2c, 0x62, 0x46, 0x05, 0x6e, 0xfc, 0xd2,
	0x40, 0x7d, 0x53, 0x04, 0x2e, 0x0e, 0x88, 0x90, 0x98, 0x6f, 0x71, 0x42, 0x3d, 0x12, 0xa3, 0x1d,
	0xd8, 0x02, 0x37, 0x3c, 0x8e, 0x91, 0x64, 0xfc, 0xaf, 0x34, 0x0b, 0x20, 0x5c, 0x04, 0x7a, 0x5c,
	0x14, 0x68, 0x13, 0x5f, 0x51, 0xad, 0xb9, 0x63, 0xa5, 0x6f, 0xc3, 0x87, 0x10, 0x8c, 0x50, 0x14,
	0x61, 0x63, 0x58, 0x85, 0xd4, 0x19, 0xce, 0x80, 0x6a, 0x9c, 0x74, 0xde, 0xe2, 0xae, 0x31, 0xb2,
	0xa0, 0x35, 0x75, 0x37, 0xb7, 0xe0, 0x12, 0x98, 0xe8, 0x95, 0x93, 0xdd, 0x18, 0x1b, 0xa3, 0x2a,
	0x6b, 0xbc, 0xf4, 0xbe, 0xec, 0xc6, 0x2a, 0xdd, 0x67, 0x11, 0x22, 0xd4, 0xa8, 0xaa, 0x70, 0x6e,
	0xad, 0xea, 0xa9, 0x5e, 0xc5, 0x6c, 0x0d, 0x0b, 0xdc, 0x1a, 0xc4, 0xb3, 0x14, 0xe2, 0xd3, 0x90,
	0x12, 0x69, 0x3b, 0xe9, 0x44, 0x44, 0x6e, 0x95, 0x5a, 0x3e, 0x67, 0x3e, 0xfe, 0x2f, 0x2d, 0xee,
	0x80, 0x49, 0x8f, 0x51, 0x89, 0xa9, 0x6c, 0x87, 0x48, 0x84, 0x6d, 0x42, 0x95, 0x1c, 0xba, 0x3b,
	0x9e, 0xbb, 0x9f, 0x22, 0x11, 0x6e, 0x50, 0xd8, 0x04, 0x53, 0xe7, 0x70, 0x2c, 0x91, 0x4a, 0x1c,
	0xdd, 0x9d, 0x38, 0x03, 0x7c, 0x91, 0x48, 0xe8, 0x80, 0x9b, 0x92, 0x23, 0x2a, 0xde, 0x30, 0x1e,
	0x21, 0x49, 0x18, 0xcd, 0x34, 0x19, 0x51, 0xa4, 0xe1, 0xf9, 0x90, 0x12, 0xa6, 0xff, 0x3a, 0x46,
	0x2f, 0x5e, 0xc7, 0x14, 0x18, 0x16, 0x24, 0x50, 0xc2, 0xe9, 0x6e, 0x7a, 0xec, 0x53, 0x6d, 0x11,
	0xcc, 0x5f, 0x22, 0x4a, 0x21, 0x5c, 0xeb, 0xf7, 0x10, 0x18, 0xde, 0x14, 0x01, 0x0c, 0x81, 0x7e,
	0xee, 0x4f, 0xb9, 0x7b, 0xd9, 0x86, 0xf7, 0xad, 0xa2, 0xe9, 0xfc, 0x23, 0xb0, 0xe8, 0x08, 0xdf,
	0x81, 0xe9, 0x8b, 0xfb, 0x7a, 0xef, 0x8a, 0x2a, 0x17, 0xd0, 0xe6, 0xc3, 0xeb, 0xa0, 0xcb, 0xc6,
	0xfb, 0x1a, 0xa8, 0x0f, 0x5c, 0x90, 0xab, 0x28, 0x0c, 0x4a, 0x30, 0x1f, 0x5f, 0x33, 0xa1, 0x18,
	0xc1, 0x1c, 0xdd, 0x4f, 0xdf, 0x84, 0xf5, 0x67, 0x87, 0xc7, 0x96, 0x76, 0x74, 0x6c, 0x69, 0x3f,
	0x8f, 0x2d, 0xed, 0xe3, 0x89, 0x55, 0x39, 0x3a, 0xb1, 0x2a, 0xdf, 0x4f, 0xac, 0xca, 0xeb, 0x56,
	0x40, 0x64, 0x98, 0x74, 0x6c, 0x8f, 0x45, 0x8e, 0x48, 0xb8, 0x7a, 0xc9, 0x3c, 0xb6, 0xe3, 0x0c,
	0x7e, 0x29, 0xd2, 0x0d, 0x12, 0x9d, 0xaa, 0x42, 0x3d, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x5a,
	0x60, 0x01, 0x94, 0xac, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// RegisterPrincipal registers a new pipeline principal.
	RegisterPrincipal(ctx context.Context, in *MsgRegisterPrincipal, opts ...grpc.CallOption) (*MsgRegisterPrincipalResponse, error)
	// SubmitProvenanceNode submits a provenance node linking input to output content.
	SubmitProvenanceNode(ctx context.Context, in *MsgSubmitProvenanceNode, opts ...grpc.CallOption) (*MsgSubmitProvenanceNodeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/surchain.provenance.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterPrincipal(ctx context.Context, in *MsgRegisterPrincipal, opts ...grpc.CallOption) (*MsgRegisterPrincipalResponse, error) {
	out := new(MsgRegisterPrincipalResponse)
	err := c.cc.Invoke(ctx, "/surchain.provenance.v1.Msg/RegisterPrincipal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitProvenanceNode(ctx context.Context, in *MsgSubmitProvenanceNode, opts ...grpc.CallOption) (*MsgSubmitProvenanceNodeResponse, error) {
	out := new(MsgSubmitProvenanceNodeResponse)
	err := c.cc.Invoke(ctx, "/surchain.provenance.v1.Msg/SubmitProvenanceNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// RegisterPrincipal registers a new pipeline principal.
	RegisterPrincipal(context.Context, *MsgRegisterPrincipal) (*MsgRegisterPrincipalResponse, error)
	// SubmitProvenanceNode submits a provenance node linking input to output content.
	SubmitProvenanceNode(context.Context, *MsgSubmitProvenanceNode) (*MsgSubmitProvenanceNodeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) RegisterPrincipal(ctx context.Context, req *MsgRegisterPrincipal) (*MsgRegisterPrincipalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPrincipal not implemented")
}
func (*UnimplementedMsgServer) SubmitProvenanceNode(ctx context.Context, req *MsgSubmitProvenanceNode) (*MsgSubmitProvenanceNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitProvenanceNode not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.provenance.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterPrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterPrincipal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterPrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.provenance.v1.Msg/RegisterPrincipal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterPrincipal(ctx, req.(*MsgRegisterPrincipal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitProvenanceNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitProvenanceNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitProvenanceNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.provenance.v1.Msg/SubmitProvenanceNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitProvenanceNode(ctx, req.(*MsgSubmitProvenanceNode))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "surchain.provenance.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterPrincipal",
			Handler:    _Msg_RegisterPrincipal_Handler,
		},
		{
			MethodName: "SubmitProvenanceNode",
			Handler:    _Msg_SubmitProvenanceNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "surchain/provenance/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegisterPrincipal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterPrincipal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterPrincipal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.PrincipalType) > 0 {
		i -= len(m.PrincipalType)
		copy(dAtA[i:], m.PrincipalType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PrincipalType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Pubkey) > 0 {
		i -= len(m.Pubkey)
		copy(dAtA[i:], m.Pubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Pubkey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PrincipalId) > 0 {
		i -= len(m.PrincipalId)
		copy(dAtA[i:], m.PrincipalId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PrincipalId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterPrincipalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterPrincipalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterPrincipalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitProvenanceNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitProvenanceNode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitProvenanceNode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sig) > 0 {
		i -= len(m.Sig)
		copy(dAtA[i:], m.Sig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sig)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.PrincipalId) > 0 {
		i -= len(m.PrincipalId)
		copy(dAtA[i:], m.PrincipalId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PrincipalId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TransformationType) > 0 {
		i -= len(m.TransformationType)
		copy(dAtA[i:], m.TransformationType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TransformationType)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ContentHashOut) > 0 {
		i -= len(m.ContentHashOut)
		copy(dAtA[i:], m.ContentHashOut)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContentHashOut)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ContentHashIn) > 0 {
		i -= len(m.ContentHashIn)
		copy(dAtA[i:], m.ContentHashIn)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContentHashIn)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitProvenanceNodeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitProvenanceNodeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitProvenanceNodeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegisterPrincipal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PrincipalId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Pubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PrincipalType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterPrincipalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitProvenanceNode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContentHashIn)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContentHashOut)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TransformationType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PrincipalId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Sig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitProvenanceNodeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterPrincipal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterPrincipal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterPrincipal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrincipalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrincipalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkey = append(m.Pubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.Pubkey == nil {
				m.Pubkey = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrincipalType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrincipalType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterPrincipalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterPrincipalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterPrincipalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitProvenanceNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitProvenanceNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitProvenanceNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHashIn", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHashIn = append(m.ContentHashIn[:0], dAtA[iNdEx:postIndex]...)
			if m.ContentHashIn == nil {
				m.ContentHashIn = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHashOut", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHashOut = append(m.ContentHashOut[:0], dAtA[iNdEx:postIndex]...)
			if m.ContentHashOut == nil {
				m.ContentHashOut = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransformationType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransformationType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrincipalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrincipalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sig = append(m.Sig[:0], dAtA[iNdEx:postIndex]...)
			if m.Sig == nil {
				m.Sig = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitProvenanceNodeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitProvenanceNodeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitProvenanceNodeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
