// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: surchain/identity/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf72fa8cb434440, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf72fa8cb434440, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetUserProfileRequest is the request type for GetUserProfile.
type QueryGetUserProfileRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (m *QueryGetUserProfileRequest) Reset()         { *m = QueryGetUserProfileRequest{} }
func (m *QueryGetUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserProfileRequest) ProtoMessage()    {}
func (*QueryGetUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf72fa8cb434440, []int{2}
}
func (m *QueryGetUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserProfileRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserProfileRequest.Merge(m, src)
}
func (m *QueryGetUserProfileRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserProfileRequest proto.InternalMessageInfo

func (m *QueryGetUserProfileRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// QueryGetUserProfileResponse is the response type for GetUserProfile.
type QueryGetUserProfileResponse struct {
	Username         string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ControlKeyHash   []byte `protobuf:"bytes,2,opt,name=control_key_hash,json=controlKeyHash,proto3" json:"control_key_hash,omitempty"`
	RegisteredAt     int64  `protobuf:"varint,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	CommitmentRoot   []byte `protobuf:"bytes,4,opt,name=commitment_root,json=commitmentRoot,proto3" json:"commitment_root,omitempty"`
	DeviceCount      uint64 `protobuf:"varint,5,opt,name=device_count,json=deviceCount,proto3" json:"device_count,omitempty"`
	TotalDeviceCount uint64 `protobuf:"varint,6,opt,name=total_device_count,json=totalDeviceCount,proto3" json:"total_device_count,omitempty"`
}

func (m *QueryGetUserProfileResponse) Reset()         { *m = QueryGetUserProfileResponse{} }
func (m *QueryGetUserProfileResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserProfileResponse) ProtoMessage()    {}
func (*QueryGetUserProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf72fa8cb434440, []int{3}
}
func (m *QueryGetUserProfileResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserProfileResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserProfileResponse.Merge(m, src)
}
func (m *QueryGetUserProfileResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserProfileResponse proto.InternalMessageInfo

func (m *QueryGetUserProfileResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryGetUserProfileResponse) GetControlKeyHash() []byte {
	if m != nil {
		return m.ControlKeyHash
	}
	return nil
}

func (m *QueryGetUserProfileResponse) GetRegisteredAt() int64 {
	if m != nil {
		return m.RegisteredAt
	}
	return 0
}

func (m *QueryGetUserProfileResponse) GetCommitmentRoot() []byte {
	if m != nil {
		return m.CommitmentRoot
	}
	return nil
}

func (m *QueryGetUserProfileResponse) GetDeviceCount() uint64 {
	if m != nil {
		return m.DeviceCount
	}
	return 0
}

func (m *QueryGetUserProfileResponse) GetTotalDeviceCount() uint64 {
	if m != nil {
		return m.TotalDeviceCount
	}
	return 0
}

// QueryGetDeviceCommitmentRequest is the request type for GetDeviceCommitment.
type QueryGetDeviceCommitmentRequest struct {
	Username    string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	DeviceIndex uint64 `protobuf:"varint,2,opt,name=device_index,json=deviceIndex,proto3" json:"device_index,omitempty"`
}

func (m *QueryGetDeviceCommitmentRequest) Reset()         { *m = QueryGetDeviceCommitmentRequest{} }
func (m *QueryGetDeviceCommitmentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDeviceCommitmentRequest) ProtoMessage()    {}
func (*QueryGetDeviceCommitmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf72fa8cb434440, []int{4}
}
func (m *QueryGetDeviceCommitmentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDeviceCommitmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDeviceCommitmentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDeviceCommitmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDeviceCommitmentRequest.Merge(m, src)
}
func (m *QueryGetDeviceCommitmentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDeviceCommitmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDeviceCommitmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDeviceCommitmentRequest proto.InternalMessageInfo

func (m *QueryGetDeviceCommitmentRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryGetDeviceCommitmentRequest) GetDeviceIndex() uint64 {
	if m != nil {
		return m.DeviceIndex
	}
	return 0
}

// QueryGetDeviceCommitmentResponse is the response type for GetDeviceCommitment.
type QueryGetDeviceCommitmentResponse struct {
	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	AddedAt    int64  `protobuf:"varint,2,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	Revoked    bool   `protobuf:"varint,3,opt,name=revoked,proto3" json:"revoked,omitempty"`
}

func (m *QueryGetDeviceCommitmentResponse) Reset()         { *m = QueryGetDeviceCommitmentResponse{} }
func (m *QueryGetDeviceCommitmentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDeviceCommitmentResponse) ProtoMessage()    {}
func (*QueryGetDeviceCommitmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daf72fa8cb434440, []int{5}
}
func (m *QueryGetDeviceCommitmentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDeviceCommitmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDeviceCommitmentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDeviceCommitmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDeviceCommitmentResponse.Merge(m, src)
}
func (m *QueryGetDeviceCommitmentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDeviceCommitmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDeviceCommitmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDeviceCommitmentResponse proto.InternalMessageInfo

func (m *QueryGetDeviceCommitmentResponse) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

func (m *QueryGetDeviceCommitmentResponse) GetAddedAt() int64 {
	if m != nil {
		return m.AddedAt
	}
	return 0
}

func (m *QueryGetDeviceCommitmentResponse) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "surchain.identity.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "surchain.identity.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetUserProfileRequest)(nil), "surchain.identity.v1.QueryGetUserProfileRequest")
	proto.RegisterType((*QueryGetUserProfileResponse)(nil), "surchain.identity.v1.QueryGetUserProfileResponse")
	proto.RegisterType((*QueryGetDeviceCommitmentRequest)(nil), "surchain.identity.v1.QueryGetDeviceCommitmentRequest")
	proto.RegisterType((*QueryGetDeviceCommitmentResponse)(nil), "surchain.identity.v1.QueryGetDeviceCommitmentResponse")
}

func init() { proto.RegisterFile("surchain/identity/v1/query.proto", fileDescriptor_daf72fa8cb434440) }

var fileDescriptor_daf72fa8cb434440 = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x4f, 0xd4, 0x40,
	0x18, 0xdd, 0x2e, 0xb0, 0xc0, 0xb0, 0x22, 0x0e, 0x1c, 0xd6, 0x4a, 0xca, 0x52, 0x0f, 0x56, 0x62,
	0x76, 0x58, 0x54, 0xe2, 0xc1, 0xc4, 0x80, 0x24, 0x2a, 0x5e, 0xb0, 0x89, 0x1e, 0xbc, 0xac, 0xb3,
	0xed, 0xd8, 0x9d, 0xb0, 0x9d, 0x29, 0x33, 0xd3, 0x95, 0x0d, 0xe1, 0xc2, 0x1f, 0xd0, 0xc4, 0x7f,
	0xe0, 0xc9, 0xa3, 0x89, 0x7f, 0x82, 0x23, 0x89, 0x17, 0x4f, 0xc6, 0x80, 0x89, 0x7f, 0xc3, 0xec,
	0xb4, 0x65, 0x97, 0x58, 0x16, 0xb8, 0x34, 0x9d, 0xd7, 0xf7, 0x7d, 0xef, 0x7d, 0x5f, 0xdf, 0x80,
	0xaa, 0x8c, 0x85, 0xd7, 0xc2, 0x94, 0x21, 0xea, 0x13, 0xa6, 0xa8, 0xea, 0xa2, 0x4e, 0x1d, 0xed,
	0xc4, 0x44, 0x74, 0x6b, 0x91, 0xe0, 0x8a, 0xc3, 0xb9, 0x8c, 0x51, 0xcb, 0x18, 0xb5, 0x4e, 0xdd,
	0xbc, 0x81, 0x43, 0xca, 0x38, 0xd2, 0xcf, 0x84, 0x68, 0xce, 0x05, 0x3c, 0xe0, 0xfa, 0x15, 0xf5,
	0xde, 0x52, 0x74, 0x3e, 0xe0, 0x3c, 0x68, 0x13, 0x84, 0x23, 0x8a, 0x30, 0x63, 0x5c, 0x61, 0x45,
	0x39, 0x93, 0xe9, 0xd7, 0x25, 0x8f, 0xcb, 0x90, 0x4b, 0xd4, 0xc4, 0x92, 0x24, 0xaa, 0xa8, 0x53,
	0x6f, 0x12, 0x85, 0xeb, 0x28, 0xc2, 0x01, 0x65, 0x9a, 0x9c, 0x72, 0x17, 0x73, 0xad, 0x46, 0x58,
	0xe0, 0x30, 0x6d, 0x67, 0xcf, 0x01, 0xf8, 0xaa, 0xd7, 0x64, 0x4b, 0x83, 0x2e, 0xd9, 0x89, 0x89,
	0x54, 0xf6, 0x1b, 0x30, 0x7b, 0x06, 0x95, 0x11, 0x67, 0x92, 0xc0, 0x27, 0xa0, 0x94, 0x14, 0x57,
	0x8c, 0xaa, 0xe1, 0x4c, 0xad, 0xcc, 0xd7, 0xf2, 0x26, 0xad, 0x25, 0x55, 0xeb, 0x93, 0x87, 0xbf,
	0x16, 0x0a, 0x5f, 0xff, 0x7e, 0x5b, 0x32, 0xdc, 0xb4, 0xcc, 0x7e, 0x04, 0x4c, 0xdd, 0xf7, 0x19,
	0x51, 0xaf, 0x25, 0x11, 0x5b, 0x82, 0xbf, 0xa7, 0x6d, 0x92, 0xaa, 0x42, 0x13, 0x4c, 0xc4, 0x92,
	0x08, 0x86, 0x43, 0xa2, 0x05, 0x26, 0xdd, 0xd3, 0xb3, 0x7d, 0x50, 0x04, 0xb7, 0x72, 0x4b, 0x53,
	0x6b, 0x43, 0x6a, 0xa1, 0x03, 0x66, 0x3c, 0xce, 0x94, 0xe0, 0xed, 0xc6, 0x36, 0xe9, 0x36, 0x5a,
	0x58, 0xb6, 0x2a, 0xc5, 0xaa, 0xe1, 0x94, 0xdd, 0xe9, 0x14, 0x7f, 0x49, 0xba, 0xcf, 0xb1, 0x6c,
	0xc1, 0xdb, 0xe0, 0x9a, 0x20, 0x01, 0x95, 0x8a, 0x08, 0xe2, 0x37, 0xb0, 0xaa, 0x8c, 0x54, 0x0d,
	0x67, 0xc4, 0x2d, 0xf7, 0xc1, 0x35, 0x05, 0xef, 0x80, 0xeb, 0x1e, 0x0f, 0x43, 0xaa, 0x42, 0xc2,
	0x54, 0x43, 0x70, 0xae, 0x2a, 0xa3, 0x59, 0xb7, 0x0c, 0x76, 0x39, 0x57, 0x70, 0x11, 0x94, 0x7d,
	0xd2, 0xa1, 0x1e, 0x69, 0x78, 0x3c, 0x66, 0xaa, 0x32, 0x56, 0x35, 0x9c, 0x51, 0x77, 0x2a, 0xc1,
	0x9e, 0xf6, 0x20, 0x78, 0x0f, 0x40, 0xc5, 0x15, 0x6e, 0x37, 0xce, 0x10, 0x4b, 0x9a, 0x38, 0xa3,
	0xbf, 0x6c, 0xf4, 0xd9, 0xf6, 0x3b, 0xb0, 0x90, 0xed, 0x20, 0x83, 0x4f, 0x05, 0x2f, 0xde, 0xe1,
	0x80, 0x1f, 0xca, 0x7c, 0xb2, 0xab, 0x77, 0x70, 0xea, 0xe7, 0x45, 0x0f, 0xb2, 0x3f, 0x80, 0xea,
	0xf9, 0x0a, 0xe9, 0xaa, 0x2d, 0x00, 0xfa, 0x83, 0x6a, 0x91, 0xb2, 0x3b, 0x80, 0xc0, 0x9b, 0x60,
	0x02, 0xfb, 0x7e, 0xb2, 0xbf, 0xa2, 0xde, 0xdf, 0xb8, 0x3e, 0xaf, 0x29, 0x58, 0x01, 0xe3, 0x82,
	0x74, 0xf8, 0x36, 0xf1, 0xf5, 0x66, 0x27, 0xdc, 0xec, 0xb8, 0xf2, 0x65, 0x14, 0x8c, 0x69, 0x65,
	0xf8, 0xd1, 0x00, 0xa5, 0x24, 0x41, 0xd0, 0xc9, 0xcf, 0xd7, 0xff, 0x81, 0x35, 0xef, 0x5e, 0x82,
	0x99, 0xd8, 0xb7, 0x97, 0x0f, 0x7e, 0xfc, 0xf9, 0x5c, 0x5c, 0x82, 0x0e, 0x92, 0xb1, 0xd0, 0x97,
	0xc0, 0xe3, 0x6d, 0x34, 0xe4, 0xa6, 0xc0, 0xef, 0x06, 0x98, 0x3e, 0x1b, 0x3b, 0xb8, 0x3c, 0x44,
	0x2f, 0x37, 0xdc, 0x66, 0xfd, 0x0a, 0x15, 0xa9, 0xd3, 0xc7, 0xda, 0xe9, 0x2a, 0x7c, 0x70, 0x09,
	0xa7, 0x49, 0x29, 0xda, 0xcb, 0x7e, 0xf6, 0x3e, 0x3c, 0x32, 0xc0, 0x6c, 0xce, 0x6f, 0x84, 0x0f,
	0x87, 0x1b, 0x39, 0x27, 0x58, 0xe6, 0xea, 0x55, 0xcb, 0xd2, 0x21, 0x36, 0xf5, 0x10, 0x1b, 0x70,
	0xfd, 0xe2, 0x21, 0x92, 0x20, 0x0e, 0xcc, 0x80, 0xf6, 0x06, 0xf3, 0xba, 0xbf, 0xbe, 0x79, 0x78,
	0x6c, 0x19, 0x47, 0xc7, 0x96, 0xf1, 0xfb, 0xd8, 0x32, 0x3e, 0x9d, 0x58, 0x85, 0xa3, 0x13, 0xab,
	0xf0, 0xf3, 0xc4, 0x2a, 0xbc, 0x5d, 0x0e, 0xa8, 0x6a, 0xc5, 0xcd, 0x9a, 0xc7, 0xc3, 0x7c, 0x9d,
	0xdd, 0xbe, 0x92, 0xea, 0x46, 0x44, 0x36, 0x4b, 0x9a, 0x73, 0xff, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf8, 0x41, 0xee, 0x50, 0xcf, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// GetUserProfile queries a user profile by username.
	GetUserProfile(ctx context.Context, in *QueryGetUserProfileRequest, opts ...grpc.CallOption) (*QueryGetUserProfileResponse, error)
	// GetDeviceCommitment queries a device commitment for a user at a given index.
	GetDeviceCommitment(ctx context.Context, in *QueryGetDeviceCommitmentRequest, opts ...grpc.CallOption) (*QueryGetDeviceCommitmentResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/surchain.identity.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetUserProfile(ctx context.Context, in *QueryGetUserProfileRequest, opts ...grpc.CallOption) (*QueryGetUserProfileResponse, error) {
	out := new(QueryGetUserProfileResponse)
	err := c.cc.Invoke(ctx, "/surchain.identity.v1.Query/GetUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDeviceCommitment(ctx context.Context, in *QueryGetDeviceCommitmentRequest, opts ...grpc.CallOption) (*QueryGetDeviceCommitmentResponse, error) {
	out := new(QueryGetDeviceCommitmentResponse)
	err := c.cc.Invoke(ctx, "/surchain.identity.v1.Query/GetDeviceCommitment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// GetUserProfile queries a user profile by username.
	GetUserProfile(context.Context, *QueryGetUserProfileRequest) (*QueryGetUserProfileResponse, error)
	// GetDeviceCommitment queries a device commitment for a user at a given index.
	GetDeviceCommitment(context.Context, *QueryGetDeviceCommitmentRequest) (*QueryGetDeviceCommitmentResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetUserProfile(ctx context.Context, req *QueryGetUserProfileRequest) (*QueryGetUserProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (*UnimplementedQueryServer) GetDeviceCommitment(ctx context.Context, req *QueryGetDeviceCommitmentRequest) (*QueryGetDeviceCommitmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceCommitment not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.identity.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.identity.v1.Query/GetUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetUserProfile(ctx, req.(*QueryGetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDeviceCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDeviceCommitmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDeviceCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.identity.v1.Query/GetDeviceCommitment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDeviceCommitment(ctx, req.(*QueryGetDeviceCommitmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "surchain.identity.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _Query_GetUserProfile_Handler,
		},
		{
			MethodName: "GetDeviceCommitment",
			Handler:    _Query_GetDeviceCommitment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "surchain/identity/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetUserProfileRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserProfileRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserProfileRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUserProfileResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserProfileResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserProfileResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalDeviceCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalDeviceCount))
		i--
		dAtA[i] = 0x30
	}
	if m.DeviceCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.DeviceCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.CommitmentRoot) > 0 {
		i -= len(m.CommitmentRoot)
		copy(dAtA[i:], m.CommitmentRoot)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CommitmentRoot)))
		i--
		dAtA[i] = 0x22
	}
	if m.RegisteredAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RegisteredAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ControlKeyHash) > 0 {
		i -= len(m.ControlKeyHash)
		copy(dAtA[i:], m.ControlKeyHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ControlKeyHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDeviceCommitmentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDeviceCommitmentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDeviceCommitmentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeviceIndex != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.DeviceIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDeviceCommitmentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDeviceCommitmentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDeviceCommitmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Revoked {
		i--
		if m.Revoked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.AddedAt != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AddedAt))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetUserProfileRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetUserProfileResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ControlKeyHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.RegisteredAt != 0 {
		n += 1 + sovQuery(uint64(m.RegisteredAt))
	}
	l = len(m.CommitmentRoot)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.DeviceCount != 0 {
		n += 1 + sovQuery(uint64(m.DeviceCount))
	}
	if m.TotalDeviceCount != 0 {
		n += 1 + sovQuery(uint64(m.TotalDeviceCount))
	}
	return n
}

func (m *QueryGetDeviceCommitmentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.DeviceIndex != 0 {
		n += 1 + sovQuery(uint64(m.DeviceIndex))
	}
	return n
}

func (m *QueryGetDeviceCommitmentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AddedAt != 0 {
		n += 1 + sovQuery(uint64(m.AddedAt))
	}
	if m.Revoked {
		n += 2
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserProfileRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserProfileRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserProfileRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserProfileResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserProfileResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserProfileResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControlKeyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ControlKeyHash = append(m.ControlKeyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ControlKeyHash == nil {
				m.ControlKeyHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			m.RegisteredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentRoot = append(m.CommitmentRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitmentRoot == nil {
				m.CommitmentRoot = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceCount", wireType)
			}
			m.DeviceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeviceCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDeviceCount", wireType)
			}
			m.TotalDeviceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalDeviceCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDeviceCommitmentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDeviceCommitmentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDeviceCommitmentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceIndex", wireType)
			}
			m.DeviceIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeviceIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDeviceCommitmentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDeviceCommitmentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDeviceCommitmentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddedAt", wireType)
			}
			m.AddedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AddedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revoked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Revoked = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
