// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: surchain/identity/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the module parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bd4c8aa5a78d6f, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bd4c8aa5a78d6f, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgRegisterUsername registers a new username with an initial device commitment.
type MsgRegisterUsername struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Username        string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ControlPubkey   []byte `protobuf:"bytes,3,opt,name=control_pubkey,json=controlPubkey,proto3" json:"control_pubkey,omitempty"`
	FirstCommitment []byte `protobuf:"bytes,4,opt,name=first_commitment,json=firstCommitment,proto3" json:"first_commitment,omitempty"`
	IdentitySig     []byte `protobuf:"bytes,5,opt,name=identity_sig,json=identitySig,proto3" json:"identity_sig,omitempty"`
	Payload         []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *MsgRegisterUsername) Reset()         { *m = MsgRegisterUsername{} }
func (m *MsgRegisterUsername) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterUsername) ProtoMessage()    {}
func (*MsgRegisterUsername) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bd4c8aa5a78d6f, []int{2}
}
func (m *MsgRegisterUsername) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterUsername) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterUsername.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterUsername) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterUsername.Merge(m, src)
}
func (m *MsgRegisterUsername) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterUsername) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterUsername.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterUsername proto.InternalMessageInfo

func (m *MsgRegisterUsername) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterUsername) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MsgRegisterUsername) GetControlPubkey() []byte {
	if m != nil {
		return m.ControlPubkey
	}
	return nil
}

func (m *MsgRegisterUsername) GetFirstCommitment() []byte {
	if m != nil {
		return m.FirstCommitment
	}
	return nil
}

func (m *MsgRegisterUsername) GetIdentitySig() []byte {
	if m != nil {
		return m.IdentitySig
	}
	return nil
}

func (m *MsgRegisterUsername) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// MsgRegisterUsernameResponse defines the response for RegisterUsername.
type MsgRegisterUsernameResponse struct {
}

func (m *MsgRegisterUsernameResponse) Reset()         { *m = MsgRegisterUsernameResponse{} }
func (m *MsgRegisterUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterUsernameResponse) ProtoMessage()    {}
func (*MsgRegisterUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bd4c8aa5a78d6f, []int{3}
}
func (m *MsgRegisterUsernameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterUsernameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterUsernameResponse.Merge(m, src)
}
func (m *MsgRegisterUsernameResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterUsernameResponse proto.InternalMessageInfo

// MsgAddDevice adds a new device commitment to an existing identity.
type MsgAddDevice struct {
	Creator       string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	NewCommitment []byte `protobuf:"bytes,3,opt,name=new_commitment,json=newCommitment,proto3" json:"new_commitment,omitempty"`
	IdentitySig   []byte `protobuf:"bytes,4,opt,name=identity_sig,json=identitySig,proto3" json:"identity_sig,omitempty"`
	Payload       []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ControlPubkey []byte `protobuf:"bytes,6,opt,name=control_pubkey,json=controlPubkey,proto3" json:"control_pubkey,omitempty"`
}

func (m *MsgAddDevice) Reset()         { *m = MsgAddDevice{} }
func (m *MsgAddDevice) String() string { return proto.CompactTextString(m) }
func (*MsgAddDevice) ProtoMessage()    {}
func (*MsgAddDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bd4c8aa5a78d6f, []int{4}
}
func (m *MsgAddDevice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddDevice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddDevice.Merge(m, src)
}
func (m *MsgAddDevice) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddDevice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddDevice proto.InternalMessageInfo

func (m *MsgAddDevice) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddDevice) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MsgAddDevice) GetNewCommitment() []byte {
	if m != nil {
		return m.NewCommitment
	}
	return nil
}

func (m *MsgAddDevice) GetIdentitySig() []byte {
	if m != nil {
		return m.IdentitySig
	}
	return nil
}

func (m *MsgAddDevice) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgAddDevice) GetControlPubkey() []byte {
	if m != nil {
		return m.ControlPubkey
	}
	return nil
}

// MsgAddDeviceResponse defines the response for AddDevice.
type MsgAddDeviceResponse struct {
}

func (m *MsgAddDeviceResponse) Reset()         { *m = MsgAddDeviceResponse{} }
func (m *MsgAddDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddDeviceResponse) ProtoMessage()    {}
func (*MsgAddDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bd4c8aa5a78d6f, []int{5}
}
func (m *MsgAddDeviceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddDeviceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddDeviceResponse.Merge(m, src)
}
func (m *MsgAddDeviceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddDeviceResponse proto.InternalMessageInfo

// MsgRevokeDevice revokes an existing device commitment.
type MsgRevokeDevice struct {
	Creator       string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DeviceIndex   uint64 `protobuf:"varint,3,opt,name=device_index,json=deviceIndex,proto3" json:"device_index,omitempty"`
	IdentitySig   []byte `protobuf:"bytes,4,opt,name=identity_sig,json=identitySig,proto3" json:"identity_sig,omitempty"`
	Payload       []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ControlPubkey []byte `protobuf:"bytes,6,opt,name=control_pubkey,json=controlPubkey,proto3" json:"control_pubkey,omitempty"`
}

func (m *MsgRevokeDevice) Reset()         { *m = MsgRevokeDevice{} }
func (m *MsgRevokeDevice) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeDevice) ProtoMessage()    {}
func (*MsgRevokeDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bd4c8aa5a78d6f, []int{6}
}
func (m *MsgRevokeDevice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevokeDevice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevokeDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeDevice.Merge(m, src)
}
func (m *MsgRevokeDevice) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeDevice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeDevice proto.InternalMessageInfo

func (m *MsgRevokeDevice) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRevokeDevice) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MsgRevokeDevice) GetDeviceIndex() uint64 {
	if m != nil {
		return m.DeviceIndex
	}
	return 0
}

func (m *MsgRevokeDevice) GetIdentitySig() []byte {
	if m != nil {
		return m.IdentitySig
	}
	return nil
}

func (m *MsgRevokeDevice) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgRevokeDevice) GetControlPubkey() []byte {
	if m != nil {
		return m.ControlPubkey
	}
	return nil
}

// MsgRevokeDeviceResponse defines the response for RevokeDevice.
type MsgRevokeDeviceResponse struct {
}

func (m *MsgRevokeDeviceResponse) Reset()         { *m = MsgRevokeDeviceResponse{} }
func (m *MsgRevokeDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRevokeDeviceResponse) ProtoMessage()    {}
func (*MsgRevokeDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bd4c8aa5a78d6f, []int{7}
}
func (m *MsgRevokeDeviceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRevokeDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRevokeDeviceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRevokeDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRevokeDeviceResponse.Merge(m, src)
}
func (m *MsgRevokeDeviceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRevokeDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRevokeDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRevokeDeviceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "surchain.identity.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "surchain.identity.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgRegisterUsername)(nil), "surchain.identity.v1.MsgRegisterUsername")
	proto.RegisterType((*MsgRegisterUsernameResponse)(nil), "surchain.identity.v1.MsgRegisterUsernameResponse")
	proto.RegisterType((*MsgAddDevice)(nil), "surchain.identity.v1.MsgAddDevice")
	proto.RegisterType((*MsgAddDeviceResponse)(nil), "surchain.identity.v1.MsgAddDeviceResponse")
	proto.RegisterType((*MsgRevokeDevice)(nil), "surchain.identity.v1.MsgRevokeDevice")
	proto.RegisterType((*MsgRevokeDeviceResponse)(nil), "surchain.identity.v1.MsgRevokeDeviceResponse")
}

func init() { proto.RegisterFile("surchain/identity/v1/tx.proto", fileDescriptor_a4bd4c8aa5a78d6f) }

var fileDescriptor_a4bd4c8aa5a78d6f = []byte{
	// 647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x3d, 0x6f, 0xd3, 0x40,
	0x18, 0x8e, 0xfb, 0x91, 0x92, 0xab, 0xa1, 0xc5, 0x44, 0xd4, 0x35, 0xd4, 0xb4, 0x41, 0x95, 0xda,
	0x48, 0xb5, 0x69, 0x91, 0x3a, 0x74, 0x41, 0x2d, 0x2c, 0x20, 0x45, 0xaa, 0x5c, 0x75, 0x81, 0x21,
	0x72, 0xed, 0xe3, 0x72, 0x6a, 0xec, 0xb3, 0xee, 0xce, 0x69, 0xb2, 0xa1, 0x8e, 0x4c, 0xfc, 0x0b,
	0x18, 0x33, 0xf0, 0x0b, 0x98, 0x3a, 0x56, 0x4c, 0x4c, 0x08, 0x25, 0x43, 0xfe, 0x01, 0xac, 0x28,
	0xe7, 0x8f, 0x7c, 0xe0, 0xa6, 0x5d, 0x2a, 0x96, 0x28, 0xf7, 0xbc, 0xcf, 0xfb, 0xf1, 0x3c, 0x97,
	0xf7, 0x02, 0x56, 0x58, 0x48, 0x9d, 0x9a, 0x8d, 0x7d, 0x13, 0xbb, 0xd0, 0xe7, 0x98, 0xb7, 0xcc,
	0xc6, 0xb6, 0xc9, 0x9b, 0x46, 0x40, 0x09, 0x27, 0x4a, 0x31, 0x09, 0x1b, 0x49, 0xd8, 0x68, 0x6c,
	0x6b, 0xf7, 0x6d, 0x0f, 0xfb, 0xc4, 0x14, 0x9f, 0x11, 0x51, 0x5b, 0x72, 0x08, 0xf3, 0x08, 0x33,
	0x3d, 0x86, 0xfa, 0x05, 0x3c, 0x86, 0xe2, 0xc0, 0x72, 0x14, 0xa8, 0x8a, 0x93, 0x19, 0x1d, 0xe2,
	0x50, 0x11, 0x11, 0x44, 0x22, 0xbc, 0xff, 0x2d, 0x46, 0xd7, 0x32, 0x27, 0x0a, 0x6c, 0x6a, 0x7b,
	0x71, 0x62, 0xe9, 0x9b, 0x04, 0x16, 0x2a, 0x0c, 0x1d, 0x07, 0xae, 0xcd, 0xe1, 0xa1, 0x88, 0x28,
	0xbb, 0xa0, 0x60, 0x87, 0xbc, 0x46, 0x28, 0xe6, 0x2d, 0x55, 0x5a, 0x95, 0x36, 0x0a, 0x07, 0xea,
	0xf7, 0xaf, 0x5b, 0xc5, 0xb8, 0xe3, 0xbe, 0xeb, 0x52, 0xc8, 0xd8, 0x11, 0xa7, 0xd8, 0x47, 0xd6,
	0x80, 0xaa, 0xbc, 0x00, 0xf9, 0xa8, 0xb6, 0x3a, 0xb5, 0x2a, 0x6d, 0xcc, 0xef, 0x3c, 0x36, 0xb2,
	0x24, 0x1b, 0x51, 0x97, 0x83, 0xc2, 0xc5, 0xcf, 0x27, 0xb9, 0x2f, 0xbd, 0x76, 0x59, 0xb2, 0xe2,
	0xb4, 0xbd, 0xdd, 0xf3, 0x5e, 0xbb, 0x3c, 0x28, 0xf8, 0xb1, 0xd7, 0x2e, 0x3f, 0x4d, 0x25, 0x34,
	0x07, 0x22, 0xc6, 0x06, 0x2e, 0x2d, 0x83, 0xa5, 0x31, 0xc8, 0x82, 0x2c, 0x20, 0x3e, 0x83, 0xa5,
	0xf3, 0x29, 0xf0, 0xa0, 0xc2, 0x90, 0x05, 0x11, 0x66, 0x1c, 0xd2, 0x63, 0x06, 0xa9, 0x6f, 0x7b,
	0x50, 0xd9, 0x01, 0x73, 0x0e, 0x85, 0x36, 0x27, 0xf4, 0x5a, 0x85, 0x09, 0x51, 0xd1, 0xc0, 0x9d,
	0x30, 0xce, 0x17, 0x0a, 0x0b, 0x56, 0x7a, 0x56, 0xd6, 0xc1, 0x3d, 0x87, 0xf8, 0x9c, 0x92, 0x7a,
	0x35, 0x08, 0x4f, 0x4e, 0x61, 0x4b, 0x9d, 0x5e, 0x95, 0x36, 0x64, 0xeb, 0x6e, 0x8c, 0x1e, 0x0a,
	0x50, 0xd9, 0x04, 0x8b, 0xef, 0x31, 0x65, 0xbc, 0xea, 0x10, 0xcf, 0xc3, 0xdc, 0x83, 0x3e, 0x57,
	0x67, 0x04, 0x71, 0x41, 0xe0, 0x2f, 0x53, 0x58, 0x59, 0x03, 0x72, 0x22, 0xb8, 0xca, 0x30, 0x52,
	0x67, 0x05, 0x6d, 0x3e, 0xc1, 0x8e, 0x30, 0x52, 0x54, 0x30, 0x17, 0xd8, 0xad, 0x3a, 0xb1, 0x5d,
	0x35, 0x2f, 0xa2, 0xc9, 0x71, 0x4f, 0xee, 0x3b, 0x99, 0x0c, 0x5e, 0x5a, 0x01, 0x8f, 0x32, 0x3c,
	0x48, 0x3d, 0xfa, 0x23, 0x01, 0xb9, 0xc2, 0xd0, 0xbe, 0xeb, 0xbe, 0x82, 0x0d, 0xec, 0xdc, 0x8a,
	0x39, 0x3e, 0x3c, 0x1b, 0xd6, 0x1c, 0x9b, 0xe3, 0xc3, 0xb3, 0x09, 0x8a, 0x67, 0x26, 0x2a, 0x9e,
	0x1d, 0x51, 0x9c, 0x71, 0x01, 0xf9, 0x8c, 0x0b, 0x18, 0x33, 0xe6, 0x21, 0x28, 0x0e, 0x0b, 0x4f,
	0x1d, 0xf9, 0x1d, 0x6d, 0x85, 0x05, 0x1b, 0xe4, 0x14, 0xde, 0x92, 0x29, 0x6b, 0x40, 0x76, 0x45,
	0xe5, 0x2a, 0xf6, 0x5d, 0xd8, 0x14, 0x96, 0xcc, 0x58, 0xf3, 0x11, 0xf6, 0xba, 0x0f, 0xfd, 0x07,
	0x43, 0xa2, 0x4d, 0x1a, 0xd6, 0x9d, 0x78, 0xb2, 0xf3, 0x79, 0x1a, 0x4c, 0x57, 0x18, 0x52, 0x5c,
	0x20, 0x8f, 0xbc, 0x16, 0xeb, 0xd9, 0x5b, 0x3e, 0xb6, 0x90, 0xda, 0xd6, 0x8d, 0x68, 0x49, 0x37,
	0x25, 0x00, 0x8b, 0xff, 0xec, 0xec, 0xe6, 0x95, 0x25, 0xc6, 0xa9, 0xda, 0xf6, 0x8d, 0xa9, 0x69,
	0xc7, 0x77, 0xa0, 0x30, 0xd8, 0x80, 0xd2, 0x95, 0xf9, 0x29, 0x47, 0x2b, 0x5f, 0xcf, 0x49, 0x8b,
	0xbb, 0x40, 0x1e, 0xf9, 0x31, 0xad, 0x4f, 0x98, 0x6f, 0x40, 0x9b, 0x60, 0x5a, 0xd6, 0x15, 0x69,
	0xb3, 0x1f, 0xfa, 0xcf, 0xe9, 0xc1, 0x9b, 0x8b, 0x8e, 0x2e, 0x5d, 0x76, 0x74, 0xe9, 0x57, 0x47,
	0x97, 0x3e, 0x75, 0xf5, 0xdc, 0x65, 0x57, 0xcf, 0xfd, 0xe8, 0xea, 0xb9, 0xb7, 0xcf, 0x10, 0xe6,
	0xb5, 0xf0, 0xc4, 0x70, 0x88, 0x67, 0xb2, 0x90, 0x8a, 0xbf, 0x00, 0x87, 0xd4, 0xcd, 0xac, 0x47,
	0x96, 0xb7, 0x02, 0xc8, 0x4e, 0xf2, 0x82, 0xf3, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6,
	0x8a, 0x9d, 0x66, 0xdd, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// RegisterUsername registers a new unique username with an initial device commitment.
	RegisterUsername(ctx context.Context, in *MsgRegisterUsername, opts ...grpc.CallOption) (*MsgRegisterUsernameResponse, error)
	// AddDevice adds a new device commitment to an existing identity.
	AddDevice(ctx context.Context, in *MsgAddDevice, opts ...grpc.CallOption) (*MsgAddDeviceResponse, error)
	// RevokeDevice revokes an existing device commitment.
	RevokeDevice(ctx context.Context, in *MsgRevokeDevice, opts ...grpc.CallOption) (*MsgRevokeDeviceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/surchain.identity.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterUsername(ctx context.Context, in *MsgRegisterUsername, opts ...grpc.CallOption) (*MsgRegisterUsernameResponse, error) {
	out := new(MsgRegisterUsernameResponse)
	err := c.cc.Invoke(ctx, "/surchain.identity.v1.Msg/RegisterUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddDevice(ctx context.Context, in *MsgAddDevice, opts ...grpc.CallOption) (*MsgAddDeviceResponse, error) {
	out := new(MsgAddDeviceResponse)
	err := c.cc.Invoke(ctx, "/surchain.identity.v1.Msg/AddDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeDevice(ctx context.Context, in *MsgRevokeDevice, opts ...grpc.CallOption) (*MsgRevokeDeviceResponse, error) {
	out := new(MsgRevokeDeviceResponse)
	err := c.cc.Invoke(ctx, "/surchain.identity.v1.Msg/RevokeDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// RegisterUsername registers a new unique username with an initial device commitment.
	RegisterUsername(context.Context, *MsgRegisterUsername) (*MsgRegisterUsernameResponse, error)
	// AddDevice adds a new device commitment to an existing identity.
	AddDevice(context.Context, *MsgAddDevice) (*MsgAddDeviceResponse, error)
	// RevokeDevice revokes an existing device commitment.
	RevokeDevice(context.Context, *MsgRevokeDevice) (*MsgRevokeDeviceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) RegisterUsername(ctx context.Context, req *MsgRegisterUsername) (*MsgRegisterUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUsername not implemented")
}
func (*UnimplementedMsgServer) AddDevice(ctx context.Context, req *MsgAddDevice) (*MsgAddDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDevice not implemented")
}
func (*UnimplementedMsgServer) RevokeDevice(ctx context.Context, req *MsgRevokeDevice) (*MsgRevokeDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeDevice not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.identity.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterUsername)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.identity.v1.Msg/RegisterUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterUsername(ctx, req.(*MsgRegisterUsername))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddDevice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.identity.v1.Msg/AddDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddDevice(ctx, req.(*MsgAddDevice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeDevice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.identity.v1.Msg/RevokeDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeDevice(ctx, req.(*MsgRevokeDevice))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "surchain.identity.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterUsername",
			Handler:    _Msg_RegisterUsername_Handler,
		},
		{
			MethodName: "AddDevice",
			Handler:    _Msg_AddDevice_Handler,
		},
		{
			MethodName: "RevokeDevice",
			Handler:    _Msg_RevokeDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "surchain/identity/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegisterUsername) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterUsername) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterUsername) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.IdentitySig) > 0 {
		i -= len(m.IdentitySig)
		copy(dAtA[i:], m.IdentitySig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.IdentitySig)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.FirstCommitment) > 0 {
		i -= len(m.FirstCommitment)
		copy(dAtA[i:], m.FirstCommitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FirstCommitment)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ControlPubkey) > 0 {
		i -= len(m.ControlPubkey)
		copy(dAtA[i:], m.ControlPubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ControlPubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterUsernameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterUsernameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterUsernameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddDevice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddDevice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddDevice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ControlPubkey) > 0 {
		i -= len(m.ControlPubkey)
		copy(dAtA[i:], m.ControlPubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ControlPubkey)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.IdentitySig) > 0 {
		i -= len(m.IdentitySig)
		copy(dAtA[i:], m.IdentitySig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.IdentitySig)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.NewCommitment) > 0 {
		i -= len(m.NewCommitment)
		copy(dAtA[i:], m.NewCommitment)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewCommitment)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddDeviceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddDeviceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddDeviceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRevokeDevice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeDevice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeDevice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ControlPubkey) > 0 {
		i -= len(m.ControlPubkey)
		copy(dAtA[i:], m.ControlPubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ControlPubkey)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.IdentitySig) > 0 {
		i -= len(m.IdentitySig)
		copy(dAtA[i:], m.IdentitySig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.IdentitySig)))
		i--
		dAtA[i] = 0x22
	}
	if m.DeviceIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DeviceIndex))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRevokeDeviceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRevokeDeviceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRevokeDeviceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegisterUsername) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ControlPubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FirstCommitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.IdentitySig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterUsernameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddDevice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewCommitment)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.IdentitySig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ControlPubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddDeviceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRevokeDevice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DeviceIndex != 0 {
		n += 1 + sovTx(uint64(m.DeviceIndex))
	}
	l = len(m.IdentitySig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ControlPubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRevokeDeviceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterUsername) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterUsername: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterUsername: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControlPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ControlPubkey = append(m.ControlPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.ControlPubkey == nil {
				m.ControlPubkey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstCommitment = append(m.FirstCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.FirstCommitment == nil {
				m.FirstCommitment = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentitySig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdentitySig = append(m.IdentitySig[:0], dAtA[iNdEx:postIndex]...)
			if m.IdentitySig == nil {
				m.IdentitySig = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterUsernameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterUsernameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterUsernameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddDevice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddDevice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddDevice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewCommitment = append(m.NewCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.NewCommitment == nil {
				m.NewCommitment = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentitySig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdentitySig = append(m.IdentitySig[:0], dAtA[iNdEx:postIndex]...)
			if m.IdentitySig == nil {
				m.IdentitySig = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControlPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ControlPubkey = append(m.ControlPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.ControlPubkey == nil {
				m.ControlPubkey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddDeviceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddDeviceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddDeviceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeDevice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeDevice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeDevice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceIndex", wireType)
			}
			m.DeviceIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeviceIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentitySig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdentitySig = append(m.IdentitySig[:0], dAtA[iNdEx:postIndex]...)
			if m.IdentitySig == nil {
				m.IdentitySig = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControlPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ControlPubkey = append(m.ControlPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.ControlPubkey == nil {
				m.ControlPubkey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRevokeDeviceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRevokeDeviceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRevokeDeviceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
