// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: surchain/identity/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// UserProfile represents a registered identity on-chain.
type UserProfile struct {
	Username         string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ControlKeyHash   []byte `protobuf:"bytes,2,opt,name=control_key_hash,json=controlKeyHash,proto3" json:"control_key_hash,omitempty"`
	RegisteredAt     int64  `protobuf:"varint,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	CommitmentRoot   []byte `protobuf:"bytes,4,opt,name=commitment_root,json=commitmentRoot,proto3" json:"commitment_root,omitempty"`
	DeviceCount      uint64 `protobuf:"varint,5,opt,name=device_count,json=deviceCount,proto3" json:"device_count,omitempty"`
	TotalDeviceCount uint64 `protobuf:"varint,6,opt,name=total_device_count,json=totalDeviceCount,proto3" json:"total_device_count,omitempty"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9f2736c27ee7428, []int{0}
}
func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return m.Size()
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserProfile) GetControlKeyHash() []byte {
	if m != nil {
		return m.ControlKeyHash
	}
	return nil
}

func (m *UserProfile) GetRegisteredAt() int64 {
	if m != nil {
		return m.RegisteredAt
	}
	return 0
}

func (m *UserProfile) GetCommitmentRoot() []byte {
	if m != nil {
		return m.CommitmentRoot
	}
	return nil
}

func (m *UserProfile) GetDeviceCount() uint64 {
	if m != nil {
		return m.DeviceCount
	}
	return 0
}

func (m *UserProfile) GetTotalDeviceCount() uint64 {
	if m != nil {
		return m.TotalDeviceCount
	}
	return 0
}

// DeviceCommitment represents a device commitment associated with a user.
type DeviceCommitment struct {
	Username   string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Index      uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Commitment []byte `protobuf:"bytes,3,opt,name=commitment,proto3" json:"commitment,omitempty"`
	AddedAt    int64  `protobuf:"varint,4,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	Revoked    bool   `protobuf:"varint,5,opt,name=revoked,proto3" json:"revoked,omitempty"`
	RevokedAt  int64  `protobuf:"varint,6,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
}

func (m *DeviceCommitment) Reset()         { *m = DeviceCommitment{} }
func (m *DeviceCommitment) String() string { return proto.CompactTextString(m) }
func (*DeviceCommitment) ProtoMessage()    {}
func (*DeviceCommitment) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9f2736c27ee7428, []int{1}
}
func (m *DeviceCommitment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceCommitment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceCommitment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceCommitment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCommitment.Merge(m, src)
}
func (m *DeviceCommitment) XXX_Size() int {
	return m.Size()
}
func (m *DeviceCommitment) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCommitment.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCommitment proto.InternalMessageInfo

func (m *DeviceCommitment) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *DeviceCommitment) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *DeviceCommitment) GetCommitment() []byte {
	if m != nil {
		return m.Commitment
	}
	return nil
}

func (m *DeviceCommitment) GetAddedAt() int64 {
	if m != nil {
		return m.AddedAt
	}
	return 0
}

func (m *DeviceCommitment) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *DeviceCommitment) GetRevokedAt() int64 {
	if m != nil {
		return m.RevokedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*UserProfile)(nil), "surchain.identity.v1.UserProfile")
	proto.RegisterType((*DeviceCommitment)(nil), "surchain.identity.v1.DeviceCommitment")
}

func init() { proto.RegisterFile("surchain/identity/v1/types.proto", fileDescriptor_c9f2736c27ee7428) }

var fileDescriptor_c9f2736c27ee7428 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xb3, 0x34, 0x4d, 0xd3, 0x69, 0x80, 0x68, 0x95, 0x83, 0xa9, 0x84, 0x65, 0xca, 0x01,
	0x1f, 0x50, 0x4c, 0xc5, 0x13, 0x04, 0x38, 0x20, 0xb8, 0xa0, 0x95, 0xb8, 0x70, 0xb1, 0x5c, 0x7b,
	0xb0, 0x57, 0xb5, 0x3d, 0xd5, 0xee, 0xd8, 0xaa, 0xdf, 0x82, 0xc7, 0xe1, 0x11, 0x38, 0xf6, 0xc8,
	0x11, 0x25, 0x6f, 0xc0, 0x13, 0xa0, 0xac, 0xe3, 0x1a, 0x2e, 0xdc, 0xe6, 0xff, 0xfd, 0x8d, 0x77,
	0xff, 0xd9, 0x81, 0xc0, 0x36, 0x26, 0x2d, 0x12, 0x5d, 0x47, 0x3a, 0xc3, 0x9a, 0x35, 0x77, 0x51,
	0x7b, 0x19, 0x71, 0x77, 0x83, 0x76, 0x7d, 0x63, 0x88, 0x49, 0xae, 0x06, 0x62, 0x3d, 0x10, 0xeb,
	0xf6, 0xf2, 0x7c, 0x95, 0x53, 0x4e, 0x0e, 0x88, 0xf6, 0x55, 0xcf, 0x5e, 0xfc, 0x16, 0x70, 0xf6,
	0xd9, 0xa2, 0xf9, 0x64, 0xe8, 0xab, 0x2e, 0x51, 0x9e, 0xc3, 0xbc, 0xb1, 0x68, 0xea, 0xa4, 0x42,
	0x4f, 0x04, 0x22, 0x3c, 0x55, 0xf7, 0x5a, 0x86, 0xb0, 0x4c, 0xa9, 0x66, 0x43, 0x65, 0x7c, 0x8d,
	0x5d, 0x5c, 0x24, 0xb6, 0xf0, 0x1e, 0x04, 0x22, 0x5c, 0xa8, 0x47, 0x07, 0xff, 0x23, 0x76, 0xef,
	0x13, 0x5b, 0xc8, 0xe7, 0xf0, 0xd0, 0x60, 0xae, 0x2d, 0xa3, 0xc1, 0x2c, 0x4e, 0xd8, 0x3b, 0x0a,
	0x44, 0x78, 0xa4, 0x16, 0xa3, 0xb9, 0x61, 0xf9, 0x02, 0x1e, 0xa7, 0x54, 0x55, 0x9a, 0x2b, 0xac,
	0x39, 0x36, 0x44, 0xec, 0x4d, 0x87, 0xbf, 0x0d, 0xb6, 0x22, 0x62, 0xf9, 0x0c, 0x16, 0x19, 0xb6,
	0x3a, 0xc5, 0x38, 0xa5, 0xa6, 0x66, 0xef, 0x38, 0x10, 0xe1, 0x54, 0x9d, 0xf5, 0xde, 0xdb, 0xbd,
	0x25, 0x5f, 0x82, 0x64, 0xe2, 0xa4, 0x8c, 0xff, 0x01, 0x67, 0x0e, 0x5c, 0xba, 0x2f, 0xef, 0x46,
	0xfa, 0xe2, 0xbb, 0x80, 0xe5, 0xa0, 0x87, 0x93, 0xfe, 0x9b, 0x7c, 0x05, 0xc7, 0xba, 0xce, 0xf0,
	0xd6, 0xc5, 0x9d, 0xaa, 0x5e, 0x48, 0x1f, 0x60, 0xbc, 0xa9, 0x8b, 0xb8, 0x50, 0x7f, 0x39, 0xf2,
	0x09, 0xcc, 0x93, 0x2c, 0xeb, 0x07, 0x30, 0x75, 0x03, 0x38, 0x71, 0x7a, 0xc3, 0xd2, 0x83, 0x13,
	0x83, 0x2d, 0x5d, 0x63, 0xe6, 0xd2, 0xcc, 0xd5, 0x20, 0xe5, 0x53, 0x80, 0x43, 0xb9, 0x6f, 0x9b,
	0xb9, 0xb6, 0xd3, 0x83, 0xb3, 0xe1, 0x37, 0x1f, 0x7e, 0x6c, 0x7d, 0x71, 0xb7, 0xf5, 0xc5, 0xaf,
	0xad, 0x2f, 0xbe, 0xed, 0xfc, 0xc9, 0xdd, 0xce, 0x9f, 0xfc, 0xdc, 0xf9, 0x93, 0x2f, 0xaf, 0x72,
	0xcd, 0x45, 0x73, 0xb5, 0x4e, 0xa9, 0x8a, 0x6c, 0x63, 0xdc, 0xf3, 0xa6, 0x54, 0x46, 0xf7, 0xeb,
	0x72, 0x3b, 0x2e, 0x8c, 0xdb, 0x96, 0xab, 0x99, 0x63, 0x5e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xe6, 0xcb, 0x76, 0x6a, 0x52, 0x02, 0x00, 0x00,
}

func (m *UserProfile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserProfile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserProfile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalDeviceCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TotalDeviceCount))
		i--
		dAtA[i] = 0x30
	}
	if m.DeviceCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.DeviceCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.CommitmentRoot) > 0 {
		i -= len(m.CommitmentRoot)
		copy(dAtA[i:], m.CommitmentRoot)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CommitmentRoot)))
		i--
		dAtA[i] = 0x22
	}
	if m.RegisteredAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RegisteredAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ControlKeyHash) > 0 {
		i -= len(m.ControlKeyHash)
		copy(dAtA[i:], m.ControlKeyHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ControlKeyHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeviceCommitment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceCommitment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceCommitment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RevokedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RevokedAt))
		i--
		dAtA[i] = 0x30
	}
	if m.Revoked {
		i--
		if m.Revoked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.AddedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AddedAt))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Index != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UserProfile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ControlKeyHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RegisteredAt != 0 {
		n += 1 + sovTypes(uint64(m.RegisteredAt))
	}
	l = len(m.CommitmentRoot)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.DeviceCount != 0 {
		n += 1 + sovTypes(uint64(m.DeviceCount))
	}
	if m.TotalDeviceCount != 0 {
		n += 1 + sovTypes(uint64(m.TotalDeviceCount))
	}
	return n
}

func (m *DeviceCommitment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovTypes(uint64(m.Index))
	}
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.AddedAt != 0 {
		n += 1 + sovTypes(uint64(m.AddedAt))
	}
	if m.Revoked {
		n += 2
	}
	if m.RevokedAt != 0 {
		n += 1 + sovTypes(uint64(m.RevokedAt))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UserProfile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserProfile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserProfile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControlKeyHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ControlKeyHash = append(m.ControlKeyHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ControlKeyHash == nil {
				m.ControlKeyHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			m.RegisteredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentRoot = append(m.CommitmentRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitmentRoot == nil {
				m.CommitmentRoot = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceCount", wireType)
			}
			m.DeviceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DeviceCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDeviceCount", wireType)
			}
			m.TotalDeviceCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalDeviceCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeviceCommitment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceCommitment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceCommitment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = append(m.Commitment[:0], dAtA[iNdEx:postIndex]...)
			if m.Commitment == nil {
				m.Commitment = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddedAt", wireType)
			}
			m.AddedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AddedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revoked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Revoked = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedAt", wireType)
			}
			m.RevokedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevokedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
