// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: surchain/attestation/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryIsNullifierUsedRequest is the request for IsNullifierUsed.
type QueryIsNullifierUsedRequest struct {
	Nullifier []byte `protobuf:"bytes,1,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
}

func (m *QueryIsNullifierUsedRequest) Reset()         { *m = QueryIsNullifierUsedRequest{} }
func (m *QueryIsNullifierUsedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryIsNullifierUsedRequest) ProtoMessage()    {}
func (*QueryIsNullifierUsedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{2}
}
func (m *QueryIsNullifierUsedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsNullifierUsedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsNullifierUsedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsNullifierUsedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsNullifierUsedRequest.Merge(m, src)
}
func (m *QueryIsNullifierUsedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsNullifierUsedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsNullifierUsedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsNullifierUsedRequest proto.InternalMessageInfo

func (m *QueryIsNullifierUsedRequest) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

// QueryIsNullifierUsedResponse is the response for IsNullifierUsed.
type QueryIsNullifierUsedResponse struct {
	Used bool `protobuf:"varint,1,opt,name=used,proto3" json:"used,omitempty"`
}

func (m *QueryIsNullifierUsedResponse) Reset()         { *m = QueryIsNullifierUsedResponse{} }
func (m *QueryIsNullifierUsedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryIsNullifierUsedResponse) ProtoMessage()    {}
func (*QueryIsNullifierUsedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{3}
}
func (m *QueryIsNullifierUsedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryIsNullifierUsedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryIsNullifierUsedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryIsNullifierUsedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryIsNullifierUsedResponse.Merge(m, src)
}
func (m *QueryIsNullifierUsedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryIsNullifierUsedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryIsNullifierUsedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryIsNullifierUsedResponse proto.InternalMessageInfo

func (m *QueryIsNullifierUsedResponse) GetUsed() bool {
	if m != nil {
		return m.Used
	}
	return false
}

// QueryGetAttestationRequest is the request for GetAttestation.
type QueryGetAttestationRequest struct {
	Username  string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nullifier []byte `protobuf:"bytes,2,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
}

func (m *QueryGetAttestationRequest) Reset()         { *m = QueryGetAttestationRequest{} }
func (m *QueryGetAttestationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAttestationRequest) ProtoMessage()    {}
func (*QueryGetAttestationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{4}
}
func (m *QueryGetAttestationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAttestationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAttestationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAttestationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAttestationRequest.Merge(m, src)
}
func (m *QueryGetAttestationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAttestationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAttestationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAttestationRequest proto.InternalMessageInfo

func (m *QueryGetAttestationRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryGetAttestationRequest) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

// QueryGetAttestationResponse is the response for GetAttestation.
type QueryGetAttestationResponse struct {
	Username    string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ContentHash []byte `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Nullifier   []byte `protobuf:"bytes,3,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	Timestamp   int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *QueryGetAttestationResponse) Reset()         { *m = QueryGetAttestationResponse{} }
func (m *QueryGetAttestationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAttestationResponse) ProtoMessage()    {}
func (*QueryGetAttestationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{5}
}
func (m *QueryGetAttestationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAttestationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAttestationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAttestationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAttestationResponse.Merge(m, src)
}
func (m *QueryGetAttestationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAttestationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAttestationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAttestationResponse proto.InternalMessageInfo

func (m *QueryGetAttestationResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *QueryGetAttestationResponse) GetContentHash() []byte {
	if m != nil {
		return m.ContentHash
	}
	return nil
}

func (m *QueryGetAttestationResponse) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

func (m *QueryGetAttestationResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// QueryVerifyContentRequest is the request for VerifyContent. content_hash_hex
// is the hex-encoded SHA-256 of the content being checked.
type QueryVerifyContentRequest struct {
	ContentHashHex string `protobuf:"bytes,1,opt,name=content_hash_hex,json=contentHashHex,proto3" json:"content_hash_hex,omitempty"`
}

func (m *QueryVerifyContentRequest) Reset()         { *m = QueryVerifyContentRequest{} }
func (m *QueryVerifyContentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVerifyContentRequest) ProtoMessage()    {}
func (*QueryVerifyContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{6}
}
func (m *QueryVerifyContentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifyContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifyContentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifyContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifyContentRequest.Merge(m, src)
}
func (m *QueryVerifyContentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifyContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifyContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifyContentRequest proto.InternalMessageInfo

func (m *QueryVerifyContentRequest) GetContentHashHex() string {
	if m != nil {
		return m.ContentHashHex
	}
	return ""
}

// AttestationMatch is one attestation bound to the queried content.
type AttestationMatch struct {
	Username       string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Nullifier      []byte `protobuf:"bytes,2,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
	CommitmentRoot []byte `protobuf:"bytes,3,opt,name=commitment_root,json=commitmentRoot,proto3" json:"commitment_root,omitempty"`
	Timestamp      int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Provenance class and optional citation (see AttestationRecord).
	Origin   string `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Citation string `protobuf:"bytes,6,opt,name=citation,proto3" json:"citation,omitempty"`
}

func (m *AttestationMatch) Reset()         { *m = AttestationMatch{} }
func (m *AttestationMatch) String() string { return proto.CompactTextString(m) }
func (*AttestationMatch) ProtoMessage()    {}
func (*AttestationMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{7}
}
func (m *AttestationMatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AttestationMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AttestationMatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AttestationMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationMatch.Merge(m, src)
}
func (m *AttestationMatch) XXX_Size() int {
	return m.Size()
}
func (m *AttestationMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationMatch.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationMatch proto.InternalMessageInfo

func (m *AttestationMatch) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AttestationMatch) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

func (m *AttestationMatch) GetCommitmentRoot() []byte {
	if m != nil {
		return m.CommitmentRoot
	}
	return nil
}

func (m *AttestationMatch) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AttestationMatch) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *AttestationMatch) GetCitation() string {
	if m != nil {
		return m.Citation
	}
	return ""
}

// QueryVerifyContentResponse is the response for VerifyContent. found is true
// when at least one attestation exists for the content; attestations lists them
// all (the same text can be attested by multiple users/sessions).
type QueryVerifyContentResponse struct {
	Found        bool                `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ContentHash  []byte              `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Attestations []*AttestationMatch `protobuf:"bytes,3,rep,name=attestations,proto3" json:"attestations,omitempty"`
}

func (m *QueryVerifyContentResponse) Reset()         { *m = QueryVerifyContentResponse{} }
func (m *QueryVerifyContentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVerifyContentResponse) ProtoMessage()    {}
func (*QueryVerifyContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{8}
}
func (m *QueryVerifyContentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifyContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifyContentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifyContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifyContentResponse.Merge(m, src)
}
func (m *QueryVerifyContentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifyContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifyContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifyContentResponse proto.InternalMessageInfo

func (m *QueryVerifyContentResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *QueryVerifyContentResponse) GetContentHash() []byte {
	if m != nil {
		return m.ContentHash
	}
	return nil
}

func (m *QueryVerifyContentResponse) GetAttestations() []*AttestationMatch {
	if m != nil {
		return m.Attestations
	}
	return nil
}

// QueryAggregateRootRequest is the request for AggregateRoot.
type QueryAggregateRootRequest struct {
}

func (m *QueryAggregateRootRequest) Reset()         { *m = QueryAggregateRootRequest{} }
func (m *QueryAggregateRootRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAggregateRootRequest) ProtoMessage()    {}
func (*QueryAggregateRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{9}
}
func (m *QueryAggregateRootRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAggregateRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAggregateRootRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAggregateRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAggregateRootRequest.Merge(m, src)
}
func (m *QueryAggregateRootRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAggregateRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAggregateRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAggregateRootRequest proto.InternalMessageInfo

// QueryAggregateRootResponse carries the keccak Merkle root over all accepted
// attestations, the number of leaves, and the chain height it reflects.
type QueryAggregateRootResponse struct {
	Root      []byte `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	LeafCount uint64 `protobuf:"varint,2,opt,name=leaf_count,json=leafCount,proto3" json:"leaf_count,omitempty"`
	Height    int64  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *QueryAggregateRootResponse) Reset()         { *m = QueryAggregateRootResponse{} }
func (m *QueryAggregateRootResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAggregateRootResponse) ProtoMessage()    {}
func (*QueryAggregateRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{10}
}
func (m *QueryAggregateRootResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAggregateRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAggregateRootResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAggregateRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAggregateRootResponse.Merge(m, src)
}
func (m *QueryAggregateRootResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAggregateRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAggregateRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAggregateRootResponse proto.InternalMessageInfo

func (m *QueryAggregateRootResponse) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *QueryAggregateRootResponse) GetLeafCount() uint64 {
	if m != nil {
		return m.LeafCount
	}
	return 0
}

func (m *QueryAggregateRootResponse) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// QueryMerkleProofRequest is the request for MerkleProof (hex SHA-256 content hash).
type QueryMerkleProofRequest struct {
	ContentHashHex string `protobuf:"bytes,1,opt,name=content_hash_hex,json=contentHashHex,proto3" json:"content_hash_hex,omitempty"`
}

func (m *QueryMerkleProofRequest) Reset()         { *m = QueryMerkleProofRequest{} }
func (m *QueryMerkleProofRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMerkleProofRequest) ProtoMessage()    {}
func (*QueryMerkleProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{11}
}
func (m *QueryMerkleProofRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMerkleProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMerkleProofRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMerkleProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMerkleProofRequest.Merge(m, src)
}
func (m *QueryMerkleProofRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMerkleProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMerkleProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMerkleProofRequest proto.InternalMessageInfo

func (m *QueryMerkleProofRequest) GetContentHashHex() string {
	if m != nil {
		return m.ContentHashHex
	}
	return ""
}

// QueryMerkleProofResponse carries an inclusion proof against the aggregate root.
type QueryMerkleProofResponse struct {
	Found bool     `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Root  []byte   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Leaf  []byte   `protobuf:"bytes,3,opt,name=leaf,proto3" json:"leaf,omitempty"`
	Proof [][]byte `protobuf:"bytes,4,rep,name=proof,proto3" json:"proof,omitempty"`
}

func (m *QueryMerkleProofResponse) Reset()         { *m = QueryMerkleProofResponse{} }
func (m *QueryMerkleProofResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMerkleProofResponse) ProtoMessage()    {}
func (*QueryMerkleProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb839314dcc0f194, []int{12}
}
func (m *QueryMerkleProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMerkleProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMerkleProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMerkleProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMerkleProofResponse.Merge(m, src)
}
func (m *QueryMerkleProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMerkleProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMerkleProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMerkleProofResponse proto.InternalMessageInfo

func (m *QueryMerkleProofResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *QueryMerkleProofResponse) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *QueryMerkleProofResponse) GetLeaf() []byte {
	if m != nil {
		return m.Leaf
	}
	return nil
}

func (m *QueryMerkleProofResponse) GetProof() [][]byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "surchain.attestation.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "surchain.attestation.v1.QueryParamsResponse")
	proto.RegisterType((*QueryIsNullifierUsedRequest)(nil), "surchain.attestation.v1.QueryIsNullifierUsedRequest")
	proto.RegisterType((*QueryIsNullifierUsedResponse)(nil), "surchain.attestation.v1.QueryIsNullifierUsedResponse")
	proto.RegisterType((*QueryGetAttestationRequest)(nil), "surchain.attestation.v1.QueryGetAttestationRequest")
	proto.RegisterType((*QueryGetAttestationResponse)(nil), "surchain.attestation.v1.QueryGetAttestationResponse")
	proto.RegisterType((*QueryVerifyContentRequest)(nil), "surchain.attestation.v1.QueryVerifyContentRequest")
	proto.RegisterType((*AttestationMatch)(nil), "surchain.attestation.v1.AttestationMatch")
	proto.RegisterType((*QueryVerifyContentResponse)(nil), "surchain.attestation.v1.QueryVerifyContentResponse")
	proto.RegisterType((*QueryAggregateRootRequest)(nil), "surchain.attestation.v1.QueryAggregateRootRequest")
	proto.RegisterType((*QueryAggregateRootResponse)(nil), "surchain.attestation.v1.QueryAggregateRootResponse")
	proto.RegisterType((*QueryMerkleProofRequest)(nil), "surchain.attestation.v1.QueryMerkleProofRequest")
	proto.RegisterType((*QueryMerkleProofResponse)(nil), "surchain.attestation.v1.QueryMerkleProofResponse")
}

func init() {
	proto.RegisterFile("surchain/attestation/v1/query.proto", fileDescriptor_eb839314dcc0f194)
}

var fileDescriptor_eb839314dcc0f194 = []byte{
	// 905 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0xdf, 0xd9, 0x64, 0xa3, 0xdd, 0xd9, 0x74, 0x5b, 0x86, 0x15, 0x0d, 0xee, 0x92, 0x06, 0x83,
	0x44, 0x68, 0xd9, 0x98, 0x24, 0xed, 0x85, 0x22, 0x44, 0xb3, 0xd0, 0x3f, 0x12, 0x81, 0x62, 0x89,
	0x4a, 0x70, 0x59, 0x4d, 0xdc, 0x89, 0x6d, 0x11, 0x7b, 0x5c, 0xcf, 0x38, 0xda, 0xd5, 0x6a, 0x2f,
	0x7c, 0x02, 0x24, 0x2e, 0xfd, 0x00, 0x1c, 0x38, 0x72, 0xe1, 0x5e, 0x71, 0xa1, 0x07, 0x0e, 0x95,
	0xb8, 0x70, 0x42, 0x68, 0x17, 0x89, 0x2f, 0xc0, 0x07, 0x40, 0x9e, 0x19, 0x6f, 0x6c, 0xaf, 0xe3,
	0x26, 0xbd, 0x58, 0xf3, 0x9e, 0xe7, 0xbd, 0xdf, 0xef, 0xf7, 0x66, 0xe6, 0x07, 0xdf, 0x62, 0x51,
	0x68, 0x39, 0xd8, 0xf5, 0x0d, 0xcc, 0x39, 0x61, 0x1c, 0x73, 0x97, 0xfa, 0xc6, 0xb4, 0x6b, 0x3c,
	0x8e, 0x48, 0x78, 0xd8, 0x09, 0x42, 0xca, 0x29, 0xba, 0x9c, 0x6c, 0xea, 0xa4, 0x36, 0x75, 0xa6,
	0x5d, 0xed, 0x15, 0xec, 0xb9, 0x3e, 0x35, 0xc4, 0x57, 0xee, 0xd5, 0xb6, 0x6d, 0x6a, 0x53, 0xb1,
	0x34, 0xe2, 0x95, 0xca, 0xee, 0xd8, 0x94, 0xda, 0x13, 0x62, 0xe0, 0xc0, 0x35, 0xb0, 0xef, 0x53,
	0xd9, 0x82, 0xa9, 0xbf, 0xd7, 0x2c, 0xca, 0x3c, 0xca, 0x8c, 0x11, 0x66, 0x44, 0x02, 0x1b, 0xd3,
	0xee, 0x88, 0x70, 0xdc, 0x35, 0x02, 0x6c, 0xbb, 0xbe, 0xc4, 0x93, 0x7b, 0xdf, 0x9e, 0x47, 0x38,
	0xc0, 0x21, 0xf6, 0x54, 0x47, 0x7d, 0x1b, 0xa2, 0x2f, 0xe3, 0x3e, 0x0f, 0x44, 0xd2, 0x24, 0x8f,
	0x23, 0xc2, 0xb8, 0xfe, 0x35, 0x7c, 0x35, 0x93, 0x65, 0x01, 0xf5, 0x19, 0x41, 0x03, 0x58, 0x93,
	0xc5, 0x0d, 0xd0, 0x02, 0xed, 0xcd, 0xde, 0xd5, 0xce, 0x1c, 0xbd, 0x1d, 0x59, 0x38, 0xd8, 0x78,
	0xf6, 0xd7, 0xd5, 0x95, 0x9f, 0xfe, 0xfd, 0xf9, 0x1a, 0x30, 0x55, 0xa5, 0x7e, 0x0b, 0x5e, 0x11,
	0xad, 0xef, 0xb3, 0xcf, 0xa3, 0xc9, 0xc4, 0x1d, 0xbb, 0x24, 0xfc, 0x8a, 0x91, 0x47, 0x0a, 0x19,
	0xed, 0xc0, 0x0d, 0x3f, 0xc9, 0x0b, 0x94, 0xba, 0x39, 0x4b, 0xe8, 0x3d, 0xb8, 0x53, 0x5c, 0xac,
	0x08, 0x22, 0x58, 0x8d, 0x18, 0x79, 0x24, 0x0a, 0xd7, 0x4d, 0xb1, 0xd6, 0x1f, 0x42, 0x4d, 0xd4,
	0xdc, 0x25, 0xfc, 0xf6, 0x8c, 0x64, 0x82, 0xa7, 0xc1, 0xf5, 0x88, 0x91, 0xd0, 0xc7, 0x1e, 0x11,
	0x55, 0x1b, 0xe6, 0x59, 0x9c, 0xe5, 0xb2, 0x9a, 0xe7, 0xf2, 0x04, 0x28, 0x25, 0xf9, 0xc6, 0x8a,
	0x4b, 0x59, 0xe7, 0x37, 0x61, 0xdd, 0xa2, 0x3e, 0x27, 0x3e, 0xdf, 0x77, 0x30, 0x73, 0x54, 0xf3,
	0x4d, 0x95, 0xbb, 0x87, 0x99, 0x93, 0x05, 0xaf, 0xe4, 0xc0, 0xe3, 0xbf, 0xdc, 0xf5, 0x62, 0x4c,
	0x2f, 0x68, 0x54, 0x5b, 0xa0, 0x5d, 0x31, 0x67, 0x09, 0xfd, 0x53, 0xf8, 0xba, 0x60, 0xf6, 0x90,
	0x84, 0xee, 0xf8, 0x70, 0x4f, 0x76, 0x4d, 0x14, 0xb7, 0xe1, 0xa5, 0x34, 0xf6, 0xbe, 0x43, 0x0e,
	0x14, 0xbf, 0xad, 0x14, 0xfe, 0x3d, 0x72, 0xa0, 0xff, 0x06, 0xe0, 0xa5, 0x94, 0xb2, 0x21, 0xe6,
	0x96, 0xf3, 0xf2, 0x03, 0x43, 0xef, 0xc0, 0x8b, 0x16, 0xf5, 0x3c, 0x97, 0x7b, 0x31, 0x76, 0x48,
	0x29, 0x57, 0xba, 0xb6, 0x66, 0x69, 0x93, 0x52, 0x5e, 0x2e, 0x0e, 0xbd, 0x06, 0x6b, 0x34, 0x74,
	0x6d, 0xd7, 0x6f, 0xac, 0x09, 0x78, 0x15, 0xc5, 0xc4, 0x2c, 0x57, 0x32, 0x6d, 0xd4, 0x24, 0xb1,
	0x24, 0xd6, 0x7f, 0x04, 0xea, 0x12, 0xe4, 0x26, 0xa2, 0x8e, 0x6a, 0x1b, 0xae, 0x8d, 0x69, 0xe4,
	0x27, 0xf7, 0x46, 0x06, 0x8b, 0x1c, 0xd2, 0x10, 0xd6, 0x53, 0x17, 0x9f, 0x35, 0x2a, 0xad, 0x4a,
	0x7b, 0xb3, 0xf7, 0xee, 0xdc, 0x67, 0x91, 0x9f, 0xa6, 0x99, 0x29, 0xd7, 0xaf, 0xa8, 0x73, 0xbb,
	0x6d, 0xdb, 0x21, 0xb1, 0x31, 0x27, 0xf1, 0x38, 0x92, 0x37, 0x69, 0x2b, 0x09, 0xb9, 0x9f, 0xb3,
	0x9b, 0x2f, 0x26, 0x2a, 0x9f, 0x8c, 0x58, 0xa3, 0x37, 0x20, 0x9c, 0x10, 0x3c, 0xde, 0xb7, 0x68,
	0xe4, 0x73, 0x41, 0xbf, 0x6a, 0x6e, 0xc4, 0x99, 0xbd, 0x38, 0x11, 0x0f, 0xd2, 0x21, 0xae, 0xed,
	0xc8, 0x63, 0xa8, 0x98, 0x2a, 0xd2, 0xf7, 0xe0, 0x65, 0x01, 0x34, 0x24, 0xe1, 0xb7, 0x13, 0xf2,
	0x20, 0xa4, 0x74, 0xbc, 0xfc, 0xdd, 0xf1, 0x61, 0xe3, 0x7c, 0x93, 0xd2, 0x71, 0x27, 0x0a, 0x56,
	0x53, 0x0a, 0x10, 0xac, 0xc6, 0x7c, 0xd5, 0x3d, 0x11, 0xeb, 0xb8, 0x3a, 0x88, 0xdb, 0x35, 0xaa,
	0xad, 0x4a, 0xbb, 0x6e, 0xca, 0xa0, 0xf7, 0xdf, 0x3a, 0x5c, 0x13, 0x80, 0xe8, 0x09, 0x80, 0x35,
	0x69, 0x3f, 0xe8, 0xfa, 0xdc, 0x83, 0x38, 0xef, 0x79, 0xda, 0x7b, 0x8b, 0x6d, 0x96, 0x1a, 0xf4,
	0xfe, 0x77, 0x7f, 0xfc, 0xf3, 0xc3, 0xea, 0x2e, 0xba, 0x6e, 0xb0, 0x28, 0x14, 0x56, 0x6a, 0xd1,
	0x89, 0x51, 0x6e, 0xb9, 0xe8, 0x57, 0x00, 0x2f, 0xe6, 0xac, 0x0b, 0xdd, 0x28, 0x87, 0x2d, 0xb6,
	0x49, 0xed, 0xe6, 0x92, 0x55, 0x8a, 0xf5, 0x40, 0xb0, 0xfe, 0x10, 0x7d, 0xb0, 0x10, 0xeb, 0xb3,
	0xa7, 0x6b, 0x1c, 0x9d, 0x2d, 0x8f, 0xd1, 0xef, 0x00, 0x6e, 0x65, 0x2d, 0x0f, 0xf5, 0xcb, 0xd9,
	0x14, 0x3a, 0xaf, 0x76, 0x63, 0xb9, 0x22, 0xa5, 0xe0, 0x0b, 0xa1, 0xe0, 0x3e, 0xba, 0xbb, 0x90,
	0x82, 0x74, 0x78, 0x94, 0xd8, 0xd4, 0x71, 0x46, 0xce, 0x53, 0x00, 0x2f, 0x64, 0x5c, 0x01, 0xf5,
	0xca, 0x89, 0x15, 0x99, 0xaa, 0xd6, 0x5f, 0xaa, 0x46, 0x69, 0xb9, 0x23, 0xb4, 0x7c, 0x8c, 0x3e,
	0x5a, 0x48, 0xcb, 0x54, 0xf4, 0x30, 0x8e, 0xf2, 0x0f, 0xf0, 0x18, 0xfd, 0x02, 0xe0, 0x85, 0x8c,
	0x2b, 0xbc, 0x48, 0x42, 0x91, 0xbf, 0xbc, 0x48, 0x42, 0xa1, 0xed, 0xe8, 0xb7, 0x84, 0x84, 0x9b,
	0xa8, 0xbf, 0xd8, 0x71, 0x24, 0x3d, 0x76, 0xc5, 0xeb, 0x7e, 0x0a, 0xe0, 0x66, 0xca, 0x1f, 0xd0,
	0xfb, 0xe5, 0x0c, 0xce, 0xfb, 0x91, 0xd6, 0x5d, 0xa2, 0x42, 0x31, 0xfe, 0x4c, 0x30, 0xbe, 0x83,
	0x3e, 0x59, 0x88, 0xb1, 0x27, 0x3a, 0xec, 0x0a, 0x8f, 0x29, 0x18, 0xfd, 0x60, 0xf8, 0xec, 0xa4,
	0x09, 0x9e, 0x9f, 0x34, 0xc1, 0xdf, 0x27, 0x4d, 0xf0, 0xfd, 0x69, 0x73, 0xe5, 0xf9, 0x69, 0x73,
	0xe5, 0xcf, 0xd3, 0xe6, 0xca, 0x37, 0x7d, 0xdb, 0xe5, 0x4e, 0x34, 0xea, 0x58, 0xd4, 0x2b, 0x46,
	0x3a, 0xc8, 0x60, 0xf1, 0xc3, 0x80, 0xb0, 0x51, 0x4d, 0x6c, 0xeb, 0xff, 0x1f, 0x00, 0x00, 0xff,
	0xff, 0xc2, 0xfc, 0xd4, 0xeb, 0x6d, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// IsNullifierUsed checks whether a nullifier has been used before.
	IsNullifierUsed(ctx context.Context, in *QueryIsNullifierUsedRequest, opts ...grpc.CallOption) (*QueryIsNullifierUsedResponse, error)
	// GetAttestation retrieves an attestation by username and nullifier.
	GetAttestation(ctx context.Context, in *QueryGetAttestationRequest, opts ...grpc.CallOption) (*QueryGetAttestationResponse, error)
	// VerifyContent checks the origin of a piece of content by its hash. Given
	// SHA-256(content) (hex), it returns every accepted human-typing attestation
	// bound to that content. This is the public provenance-verification endpoint:
	// a match proves the text was typed by a human on a registered Sur device.
	VerifyContent(ctx context.Context, in *QueryVerifyContentRequest, opts ...grpc.CallOption) (*QueryVerifyContentResponse, error)
	// AggregateRoot returns the keccak256 Merkle root over all accepted attestations
	// (the value a relayer anchors on Ethereum), plus the leaf count and the chain
	// height the snapshot reflects.
	AggregateRoot(ctx context.Context, in *QueryAggregateRootRequest, opts ...grpc.CallOption) (*QueryAggregateRootResponse, error)
	// MerkleProof returns the inclusion proof for the attestation of a given content
	// hash, against the current aggregate root — used to verify settlement on L1.
	MerkleProof(ctx context.Context, in *QueryMerkleProofRequest, opts ...grpc.CallOption) (*QueryMerkleProofResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/surchain.attestation.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IsNullifierUsed(ctx context.Context, in *QueryIsNullifierUsedRequest, opts ...grpc.CallOption) (*QueryIsNullifierUsedResponse, error) {
	out := new(QueryIsNullifierUsedResponse)
	err := c.cc.Invoke(ctx, "/surchain.attestation.v1.Query/IsNullifierUsed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAttestation(ctx context.Context, in *QueryGetAttestationRequest, opts ...grpc.CallOption) (*QueryGetAttestationResponse, error) {
	out := new(QueryGetAttestationResponse)
	err := c.cc.Invoke(ctx, "/surchain.attestation.v1.Query/GetAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerifyContent(ctx context.Context, in *QueryVerifyContentRequest, opts ...grpc.CallOption) (*QueryVerifyContentResponse, error) {
	out := new(QueryVerifyContentResponse)
	err := c.cc.Invoke(ctx, "/surchain.attestation.v1.Query/VerifyContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AggregateRoot(ctx context.Context, in *QueryAggregateRootRequest, opts ...grpc.CallOption) (*QueryAggregateRootResponse, error) {
	out := new(QueryAggregateRootResponse)
	err := c.cc.Invoke(ctx, "/surchain.attestation.v1.Query/AggregateRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MerkleProof(ctx context.Context, in *QueryMerkleProofRequest, opts ...grpc.CallOption) (*QueryMerkleProofResponse, error) {
	out := new(QueryMerkleProofResponse)
	err := c.cc.Invoke(ctx, "/surchain.attestation.v1.Query/MerkleProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// IsNullifierUsed checks whether a nullifier has been used before.
	IsNullifierUsed(context.Context, *QueryIsNullifierUsedRequest) (*QueryIsNullifierUsedResponse, error)
	// GetAttestation retrieves an attestation by username and nullifier.
	GetAttestation(context.Context, *QueryGetAttestationRequest) (*QueryGetAttestationResponse, error)
	// VerifyContent checks the origin of a piece of content by its hash. Given
	// SHA-256(content) (hex), it returns every accepted human-typing attestation
	// bound to that content. This is the public provenance-verification endpoint:
	// a match proves the text was typed by a human on a registered Sur device.
	VerifyContent(context.Context, *QueryVerifyContentRequest) (*QueryVerifyContentResponse, error)
	// AggregateRoot returns the keccak256 Merkle root over all accepted attestations
	// (the value a relayer anchors on Ethereum), plus the leaf count and the chain
	// height the snapshot reflects.
	AggregateRoot(context.Context, *QueryAggregateRootRequest) (*QueryAggregateRootResponse, error)
	// MerkleProof returns the inclusion proof for the attestation of a given content
	// hash, against the current aggregate root — used to verify settlement on L1.
	MerkleProof(context.Context, *QueryMerkleProofRequest) (*QueryMerkleProofResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) IsNullifierUsed(ctx context.Context, req *QueryIsNullifierUsedRequest) (*QueryIsNullifierUsedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsNullifierUsed not implemented")
}
func (*UnimplementedQueryServer) GetAttestation(ctx context.Context, req *QueryGetAttestationRequest) (*QueryGetAttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttestation not implemented")
}
func (*UnimplementedQueryServer) VerifyContent(ctx context.Context, req *QueryVerifyContentRequest) (*QueryVerifyContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyContent not implemented")
}
func (*UnimplementedQueryServer) AggregateRoot(ctx context.Context, req *QueryAggregateRootRequest) (*QueryAggregateRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateRoot not implemented")
}
func (*UnimplementedQueryServer) MerkleProof(ctx context.Context, req *QueryMerkleProofRequest) (*QueryMerkleProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerkleProof not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.attestation.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IsNullifierUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIsNullifierUsedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IsNullifierUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.attestation.v1.Query/IsNullifierUsed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IsNullifierUsed(ctx, req.(*QueryIsNullifierUsedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.attestation.v1.Query/GetAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAttestation(ctx, req.(*QueryGetAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerifyContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifyContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifyContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.attestation.v1.Query/VerifyContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifyContent(ctx, req.(*QueryVerifyContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AggregateRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAggregateRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AggregateRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.attestation.v1.Query/AggregateRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AggregateRoot(ctx, req.(*QueryAggregateRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MerkleProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMerkleProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MerkleProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/surchain.attestation.v1.Query/MerkleProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MerkleProof(ctx, req.(*QueryMerkleProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "surchain.attestation.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "IsNullifierUsed",
			Handler:    _Query_IsNullifierUsed_Handler,
		},
		{
			MethodName: "GetAttestation",
			Handler:    _Query_GetAttestation_Handler,
		},
		{
			MethodName: "VerifyContent",
			Handler:    _Query_VerifyContent_Handler,
		},
		{
			MethodName: "AggregateRoot",
			Handler:    _Query_AggregateRoot_Handler,
		},
		{
			MethodName: "MerkleProof",
			Handler:    _Query_MerkleProof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "surchain/attestation/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryIsNullifierUsedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsNullifierUsedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsNullifierUsedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryIsNullifierUsedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryIsNullifierUsedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryIsNullifierUsedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Used {
		i--
		if m.Used {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAttestationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAttestationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAttestationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAttestationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAttestationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAttestationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Timestamp != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ContentHash) > 0 {
		i -= len(m.ContentHash)
		copy(dAtA[i:], m.ContentHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ContentHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifyContentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifyContentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifyContentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContentHashHex) > 0 {
		i -= len(m.ContentHashHex)
		copy(dAtA[i:], m.ContentHashHex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ContentHashHex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AttestationMatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AttestationMatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AttestationMatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Citation) > 0 {
		i -= len(m.Citation)
		copy(dAtA[i:], m.Citation)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Citation)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Origin) > 0 {
		i -= len(m.Origin)
		copy(dAtA[i:], m.Origin)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Origin)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Timestamp != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.CommitmentRoot) > 0 {
		i -= len(m.CommitmentRoot)
		copy(dAtA[i:], m.CommitmentRoot)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CommitmentRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Username) > 0 {
		i -= len(m.Username)
		copy(dAtA[i:], m.Username)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Username)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifyContentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifyContentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifyContentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attestations) > 0 {
		for iNdEx := len(m.Attestations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attestations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ContentHash) > 0 {
		i -= len(m.ContentHash)
		copy(dAtA[i:], m.ContentHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ContentHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAggregateRootRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAggregateRootRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAggregateRootRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAggregateRootResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAggregateRootResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAggregateRootResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x18
	}
	if m.LeafCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LeafCount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMerkleProofRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMerkleProofRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMerkleProofRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContentHashHex) > 0 {
		i -= len(m.ContentHashHex)
		copy(dAtA[i:], m.ContentHashHex)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ContentHashHex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMerkleProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMerkleProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMerkleProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		for iNdEx := len(m.Proof) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Proof[iNdEx])
			copy(dAtA[i:], m.Proof[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Proof[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Leaf) > 0 {
		i -= len(m.Leaf)
		copy(dAtA[i:], m.Leaf)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Leaf)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x12
	}
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryIsNullifierUsedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryIsNullifierUsedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Used {
		n += 2
	}
	return n
}

func (m *QueryGetAttestationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAttestationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ContentHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovQuery(uint64(m.Timestamp))
	}
	return n
}

func (m *QueryVerifyContentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContentHashHex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *AttestationMatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Username)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.CommitmentRoot)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovQuery(uint64(m.Timestamp))
	}
	l = len(m.Origin)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Citation)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerifyContentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Found {
		n += 2
	}
	l = len(m.ContentHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Attestations) > 0 {
		for _, e := range m.Attestations {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryAggregateRootRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAggregateRootResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.LeafCount != 0 {
		n += 1 + sovQuery(uint64(m.LeafCount))
	}
	if m.Height != 0 {
		n += 1 + sovQuery(uint64(m.Height))
	}
	return n
}

func (m *QueryMerkleProofRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContentHashHex)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMerkleProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Found {
		n += 2
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Leaf)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Proof) > 0 {
		for _, b := range m.Proof {
			l = len(b)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsNullifierUsedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsNullifierUsedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsNullifierUsedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryIsNullifierUsedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryIsNullifierUsedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryIsNullifierUsedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Used", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Used = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAttestationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAttestationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAttestationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAttestationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAttestationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAttestationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHash = append(m.ContentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ContentHash == nil {
				m.ContentHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifyContentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifyContentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifyContentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHashHex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHashHex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AttestationMatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AttestationMatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AttestationMatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Username", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Username = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentRoot = append(m.CommitmentRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitmentRoot == nil {
				m.CommitmentRoot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Origin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Origin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Citation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Citation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifyContentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifyContentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifyContentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHash = append(m.ContentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ContentHash == nil {
				m.ContentHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestations = append(m.Attestations, &AttestationMatch{})
			if err := m.Attestations[len(m.Attestations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAggregateRootRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAggregateRootRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAggregateRootRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAggregateRootResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAggregateRootResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAggregateRootResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeafCount", wireType)
			}
			m.LeafCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LeafCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMerkleProofRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMerkleProofRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMerkleProofRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHashHex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHashHex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMerkleProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMerkleProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMerkleProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaf", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Leaf = append(m.Leaf[:0], dAtA[iNdEx:postIndex]...)
			if m.Leaf == nil {
				m.Leaf = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof, make([]byte, postIndex-iNdEx))
			copy(m.Proof[len(m.Proof)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
