// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: surchain/identity/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "surchain.identity.v1";

/** QueryParamsRequest is request type for the Query/Params RPC method. */
export interface QueryParamsRequest {
}

/** QueryParamsResponse is response type for the Query/Params RPC method. */
export interface QueryParamsResponse {
  /** params holds all the parameters of this module. */
  params: Params | undefined;
}

/** QueryGetUserProfileRequest is the request type for GetUserProfile. */
export interface QueryGetUserProfileRequest {
  username: string;
}

/** QueryGetUserProfileResponse is the response type for GetUserProfile. */
export interface QueryGetUserProfileResponse {
  username: string;
  controlKeyHash: Uint8Array;
  registeredAt: number;
  commitmentRoot: Uint8Array;
  deviceCount: number;
  totalDeviceCount: number;
}

/** QueryGetDeviceCommitmentRequest is the request type for GetDeviceCommitment. */
export interface QueryGetDeviceCommitmentRequest {
  username: string;
  deviceIndex: number;
}

/** QueryGetDeviceCommitmentResponse is the response type for GetDeviceCommitment. */
export interface QueryGetDeviceCommitmentResponse {
  commitment: Uint8Array;
  addedAt: number;
  revoked: boolean;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryGetUserProfileRequest(): QueryGetUserProfileRequest {
  return { username: "" };
}

export const QueryGetUserProfileRequest: MessageFns<QueryGetUserProfileRequest> = {
  encode(message: QueryGetUserProfileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetUserProfileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetUserProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetUserProfileRequest {
    return { username: isSet(object.username) ? globalThis.String(object.username) : "" };
  },

  toJSON(message: QueryGetUserProfileRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetUserProfileRequest>, I>>(base?: I): QueryGetUserProfileRequest {
    return QueryGetUserProfileRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetUserProfileRequest>, I>>(object: I): QueryGetUserProfileRequest {
    const message = createBaseQueryGetUserProfileRequest();
    message.username = object.username ?? "";
    return message;
  },
};

function createBaseQueryGetUserProfileResponse(): QueryGetUserProfileResponse {
  return {
    username: "",
    controlKeyHash: new Uint8Array(0),
    registeredAt: 0,
    commitmentRoot: new Uint8Array(0),
    deviceCount: 0,
    totalDeviceCount: 0,
  };
}

export const QueryGetUserProfileResponse: MessageFns<QueryGetUserProfileResponse> = {
  encode(message: QueryGetUserProfileResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.controlKeyHash.length !== 0) {
      writer.uint32(18).bytes(message.controlKeyHash);
    }
    if (message.registeredAt !== 0) {
      writer.uint32(24).int64(message.registeredAt);
    }
    if (message.commitmentRoot.length !== 0) {
      writer.uint32(34).bytes(message.commitmentRoot);
    }
    if (message.deviceCount !== 0) {
      writer.uint32(40).uint64(message.deviceCount);
    }
    if (message.totalDeviceCount !== 0) {
      writer.uint32(48).uint64(message.totalDeviceCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetUserProfileResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetUserProfileResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.controlKeyHash = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.registeredAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.commitmentRoot = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.deviceCount = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalDeviceCount = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetUserProfileResponse {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      controlKeyHash: isSet(object.controlKeyHash)
        ? bytesFromBase64(object.controlKeyHash)
        : isSet(object.control_key_hash)
        ? bytesFromBase64(object.control_key_hash)
        : new Uint8Array(0),
      registeredAt: isSet(object.registeredAt)
        ? globalThis.Number(object.registeredAt)
        : isSet(object.registered_at)
        ? globalThis.Number(object.registered_at)
        : 0,
      commitmentRoot: isSet(object.commitmentRoot)
        ? bytesFromBase64(object.commitmentRoot)
        : isSet(object.commitment_root)
        ? bytesFromBase64(object.commitment_root)
        : new Uint8Array(0),
      deviceCount: isSet(object.deviceCount)
        ? globalThis.Number(object.deviceCount)
        : isSet(object.device_count)
        ? globalThis.Number(object.device_count)
        : 0,
      totalDeviceCount: isSet(object.totalDeviceCount)
        ? globalThis.Number(object.totalDeviceCount)
        : isSet(object.total_device_count)
        ? globalThis.Number(object.total_device_count)
        : 0,
    };
  },

  toJSON(message: QueryGetUserProfileResponse): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.controlKeyHash.length !== 0) {
      obj.controlKeyHash = base64FromBytes(message.controlKeyHash);
    }
    if (message.registeredAt !== 0) {
      obj.registeredAt = Math.round(message.registeredAt);
    }
    if (message.commitmentRoot.length !== 0) {
      obj.commitmentRoot = base64FromBytes(message.commitmentRoot);
    }
    if (message.deviceCount !== 0) {
      obj.deviceCount = Math.round(message.deviceCount);
    }
    if (message.totalDeviceCount !== 0) {
      obj.totalDeviceCount = Math.round(message.totalDeviceCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetUserProfileResponse>, I>>(base?: I): QueryGetUserProfileResponse {
    return QueryGetUserProfileResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetUserProfileResponse>, I>>(object: I): QueryGetUserProfileResponse {
    const message = createBaseQueryGetUserProfileResponse();
    message.username = object.username ?? "";
    message.controlKeyHash = object.controlKeyHash ?? new Uint8Array(0);
    message.registeredAt = object.registeredAt ?? 0;
    message.commitmentRoot = object.commitmentRoot ?? new Uint8Array(0);
    message.deviceCount = object.deviceCount ?? 0;
    message.totalDeviceCount = object.totalDeviceCount ?? 0;
    return message;
  },
};

function createBaseQueryGetDeviceCommitmentRequest(): QueryGetDeviceCommitmentRequest {
  return { username: "", deviceIndex: 0 };
}

export const QueryGetDeviceCommitmentRequest: MessageFns<QueryGetDeviceCommitmentRequest> = {
  encode(message: QueryGetDeviceCommitmentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.deviceIndex !== 0) {
      writer.uint32(16).uint64(message.deviceIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetDeviceCommitmentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetDeviceCommitmentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.deviceIndex = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetDeviceCommitmentRequest {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      deviceIndex: isSet(object.deviceIndex)
        ? globalThis.Number(object.deviceIndex)
        : isSet(object.device_index)
        ? globalThis.Number(object.device_index)
        : 0,
    };
  },

  toJSON(message: QueryGetDeviceCommitmentRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.deviceIndex !== 0) {
      obj.deviceIndex = Math.round(message.deviceIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetDeviceCommitmentRequest>, I>>(base?: I): QueryGetDeviceCommitmentRequest {
    return QueryGetDeviceCommitmentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetDeviceCommitmentRequest>, I>>(
    object: I,
  ): QueryGetDeviceCommitmentRequest {
    const message = createBaseQueryGetDeviceCommitmentRequest();
    message.username = object.username ?? "";
    message.deviceIndex = object.deviceIndex ?? 0;
    return message;
  },
};

function createBaseQueryGetDeviceCommitmentResponse(): QueryGetDeviceCommitmentResponse {
  return { commitment: new Uint8Array(0), addedAt: 0, revoked: false };
}

export const QueryGetDeviceCommitmentResponse: MessageFns<QueryGetDeviceCommitmentResponse> = {
  encode(message: QueryGetDeviceCommitmentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.commitment.length !== 0) {
      writer.uint32(10).bytes(message.commitment);
    }
    if (message.addedAt !== 0) {
      writer.uint32(16).int64(message.addedAt);
    }
    if (message.revoked !== false) {
      writer.uint32(24).bool(message.revoked);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetDeviceCommitmentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetDeviceCommitmentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.commitment = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.addedAt = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.revoked = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetDeviceCommitmentResponse {
    return {
      commitment: isSet(object.commitment) ? bytesFromBase64(object.commitment) : new Uint8Array(0),
      addedAt: isSet(object.addedAt)
        ? globalThis.Number(object.addedAt)
        : isSet(object.added_at)
        ? globalThis.Number(object.added_at)
        : 0,
      revoked: isSet(object.revoked) ? globalThis.Boolean(object.revoked) : false,
    };
  },

  toJSON(message: QueryGetDeviceCommitmentResponse): unknown {
    const obj: any = {};
    if (message.commitment.length !== 0) {
      obj.commitment = base64FromBytes(message.commitment);
    }
    if (message.addedAt !== 0) {
      obj.addedAt = Math.round(message.addedAt);
    }
    if (message.revoked !== false) {
      obj.revoked = message.revoked;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetDeviceCommitmentResponse>, I>>(
    base?: I,
  ): QueryGetDeviceCommitmentResponse {
    return QueryGetDeviceCommitmentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetDeviceCommitmentResponse>, I>>(
    object: I,
  ): QueryGetDeviceCommitmentResponse {
    const message = createBaseQueryGetDeviceCommitmentResponse();
    message.commitment = object.commitment ?? new Uint8Array(0);
    message.addedAt = object.addedAt ?? 0;
    message.revoked = object.revoked ?? false;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** Parameters queries the parameters of the module. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** GetUserProfile queries a user profile by username. */
  GetUserProfile(request: QueryGetUserProfileRequest): Promise<QueryGetUserProfileResponse>;
  /** GetDeviceCommitment queries a device commitment for a user at a given index. */
  GetDeviceCommitment(request: QueryGetDeviceCommitmentRequest): Promise<QueryGetDeviceCommitmentResponse>;
}

export const QueryServiceName = "surchain.identity.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.GetUserProfile = this.GetUserProfile.bind(this);
    this.GetDeviceCommitment = this.GetDeviceCommitment.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  GetUserProfile(request: QueryGetUserProfileRequest): Promise<QueryGetUserProfileResponse> {
    const data = QueryGetUserProfileRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetUserProfile", data);
    return promise.then((data) => QueryGetUserProfileResponse.decode(new BinaryReader(data)));
  }

  GetDeviceCommitment(request: QueryGetDeviceCommitmentRequest): Promise<QueryGetDeviceCommitmentResponse> {
    const data = QueryGetDeviceCommitmentRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetDeviceCommitment", data);
    return promise.then((data) => QueryGetDeviceCommitmentResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
