// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: surchain/identity/v1/types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "surchain.identity.v1";

/** UserProfile represents a registered identity on-chain. */
export interface UserProfile {
  username: string;
  controlKeyHash: Uint8Array;
  registeredAt: number;
  commitmentRoot: Uint8Array;
  deviceCount: number;
  totalDeviceCount: number;
}

/** DeviceCommitment represents a device commitment associated with a user. */
export interface DeviceCommitment {
  username: string;
  index: number;
  commitment: Uint8Array;
  addedAt: number;
  revoked: boolean;
  revokedAt: number;
}

function createBaseUserProfile(): UserProfile {
  return {
    username: "",
    controlKeyHash: new Uint8Array(0),
    registeredAt: 0,
    commitmentRoot: new Uint8Array(0),
    deviceCount: 0,
    totalDeviceCount: 0,
  };
}

export const UserProfile: MessageFns<UserProfile> = {
  encode(message: UserProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.controlKeyHash.length !== 0) {
      writer.uint32(18).bytes(message.controlKeyHash);
    }
    if (message.registeredAt !== 0) {
      writer.uint32(24).int64(message.registeredAt);
    }
    if (message.commitmentRoot.length !== 0) {
      writer.uint32(34).bytes(message.commitmentRoot);
    }
    if (message.deviceCount !== 0) {
      writer.uint32(40).uint64(message.deviceCount);
    }
    if (message.totalDeviceCount !== 0) {
      writer.uint32(48).uint64(message.totalDeviceCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.controlKeyHash = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.registeredAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.commitmentRoot = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.deviceCount = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalDeviceCount = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserProfile {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      controlKeyHash: isSet(object.controlKeyHash)
        ? bytesFromBase64(object.controlKeyHash)
        : isSet(object.control_key_hash)
        ? bytesFromBase64(object.control_key_hash)
        : new Uint8Array(0),
      registeredAt: isSet(object.registeredAt)
        ? globalThis.Number(object.registeredAt)
        : isSet(object.registered_at)
        ? globalThis.Number(object.registered_at)
        : 0,
      commitmentRoot: isSet(object.commitmentRoot)
        ? bytesFromBase64(object.commitmentRoot)
        : isSet(object.commitment_root)
        ? bytesFromBase64(object.commitment_root)
        : new Uint8Array(0),
      deviceCount: isSet(object.deviceCount)
        ? globalThis.Number(object.deviceCount)
        : isSet(object.device_count)
        ? globalThis.Number(object.device_count)
        : 0,
      totalDeviceCount: isSet(object.totalDeviceCount)
        ? globalThis.Number(object.totalDeviceCount)
        : isSet(object.total_device_count)
        ? globalThis.Number(object.total_device_count)
        : 0,
    };
  },

  toJSON(message: UserProfile): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.controlKeyHash.length !== 0) {
      obj.controlKeyHash = base64FromBytes(message.controlKeyHash);
    }
    if (message.registeredAt !== 0) {
      obj.registeredAt = Math.round(message.registeredAt);
    }
    if (message.commitmentRoot.length !== 0) {
      obj.commitmentRoot = base64FromBytes(message.commitmentRoot);
    }
    if (message.deviceCount !== 0) {
      obj.deviceCount = Math.round(message.deviceCount);
    }
    if (message.totalDeviceCount !== 0) {
      obj.totalDeviceCount = Math.round(message.totalDeviceCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserProfile>, I>>(base?: I): UserProfile {
    return UserProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserProfile>, I>>(object: I): UserProfile {
    const message = createBaseUserProfile();
    message.username = object.username ?? "";
    message.controlKeyHash = object.controlKeyHash ?? new Uint8Array(0);
    message.registeredAt = object.registeredAt ?? 0;
    message.commitmentRoot = object.commitmentRoot ?? new Uint8Array(0);
    message.deviceCount = object.deviceCount ?? 0;
    message.totalDeviceCount = object.totalDeviceCount ?? 0;
    return message;
  },
};

function createBaseDeviceCommitment(): DeviceCommitment {
  return { username: "", index: 0, commitment: new Uint8Array(0), addedAt: 0, revoked: false, revokedAt: 0 };
}

export const DeviceCommitment: MessageFns<DeviceCommitment> = {
  encode(message: DeviceCommitment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.index !== 0) {
      writer.uint32(16).uint64(message.index);
    }
    if (message.commitment.length !== 0) {
      writer.uint32(26).bytes(message.commitment);
    }
    if (message.addedAt !== 0) {
      writer.uint32(32).int64(message.addedAt);
    }
    if (message.revoked !== false) {
      writer.uint32(40).bool(message.revoked);
    }
    if (message.revokedAt !== 0) {
      writer.uint32(48).int64(message.revokedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeviceCommitment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeviceCommitment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.index = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.commitment = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.addedAt = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.revoked = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.revokedAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeviceCommitment {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      commitment: isSet(object.commitment) ? bytesFromBase64(object.commitment) : new Uint8Array(0),
      addedAt: isSet(object.addedAt)
        ? globalThis.Number(object.addedAt)
        : isSet(object.added_at)
        ? globalThis.Number(object.added_at)
        : 0,
      revoked: isSet(object.revoked) ? globalThis.Boolean(object.revoked) : false,
      revokedAt: isSet(object.revokedAt)
        ? globalThis.Number(object.revokedAt)
        : isSet(object.revoked_at)
        ? globalThis.Number(object.revoked_at)
        : 0,
    };
  },

  toJSON(message: DeviceCommitment): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.commitment.length !== 0) {
      obj.commitment = base64FromBytes(message.commitment);
    }
    if (message.addedAt !== 0) {
      obj.addedAt = Math.round(message.addedAt);
    }
    if (message.revoked !== false) {
      obj.revoked = message.revoked;
    }
    if (message.revokedAt !== 0) {
      obj.revokedAt = Math.round(message.revokedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeviceCommitment>, I>>(base?: I): DeviceCommitment {
    return DeviceCommitment.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeviceCommitment>, I>>(object: I): DeviceCommitment {
    const message = createBaseDeviceCommitment();
    message.username = object.username ?? "";
    message.index = object.index ?? 0;
    message.commitment = object.commitment ?? new Uint8Array(0);
    message.addedAt = object.addedAt ?? 0;
    message.revoked = object.revoked ?? false;
    message.revokedAt = object.revokedAt ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
